- type: job
  id: PirateFirstMate
  name: job-name-pirate-first-mate
  description: job-description-pirate-first-mate
  playTimeTracker: JobPirateFirstMate
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 43200 # 12 hours Radiant_Sector
    - !type:DepartmentTimeRequirement
      department: Security
      time: 3600 # 1 hours Radiant_Sector
  startingGear: PirateFirstMateNFGear
  alwaysUseSpawner: true
  hideConsoleVisibility: true
  canBeAntag: true
  icon: "JobIconPirateFirstMate"
  supervisors: job-supervisors-captain
  weight: 30
  displayWeight: 30
  setPreference: true
  access:
  - Pirate
  accessGroups:
  - GeneralAccess
  special:
  - !type:AddComponentSpecial
    components:
    - type: MailDisabled
    - type: SpecialSectorStationRecord
      recordGeneration: FalseRecord
    - type: NpcFactionMember
      factions:
      - PirateNF
  - !type:AddImplantSpecial
    implants: [ FreelanceTrackingImplant ]
  - !type:GiveItemOnHolidaySpecial # Even pirates get a piece of cake.
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: PirateFirstMateNFGear
  equipment:
    ears: ClothingHeadsetAltFreelancer
    belt: ClothingBeltUtility
    pocket1: BasePirateUplinkPirateCrew
    pocket2: AppraisalTool
