- type: job
  id: PhoenixMedic
  name: job-name-phoenix-medic
  description: job-description-phoenix-medic
  playTimeTracker: JobPhoenixMedic
  startingGear: PhoenixMedicGear
  icon: "JobIconPhoenixMedic" 
  supervisors: job-supervisors-phoenix-cmo
  weight: 60
  displayWeight: 9
  access:
  - MedicalPhoenix
  accessGroups:
  - GeneralAccess
  special:
  - !type:AddImplantSpecial
    implants: [ EmergencyTrackingImplant ]
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift
  - !type:AddComponentSpecial
    components:
      - type: PreventShipyardTitleOverwrite

- type: startingGear
  id: PhoenixMedicGear
