- type: entity
  id: ProtolatheMachineCircuitboardAcorp
  parent: BaseMachineCircuitboard
  name: ТехФаб акорп (машинная плата)
  description: Печатная плата для ТехФаба акорп.
  components:
    - type: Sprite
      sprite: _radiant/Objects/Misc/module.rsi
      state: acorp
    - type: MachineBoard
      prototype: ProtolatheAcorp
      requirements: # Frontier
        Manipulator: 10 # Frontier stackRequirements<requirements
      tagRequirements:
        GlassBeaker:
          amount: 2
          defaultPrototype: Beaker

- type: entity
  parent: BaseComputerCircuitboard
  id: TechDiskComputerAcorpCircuitboard
  name: терминал технических документаций (машинная плата)
  description: Печатная плата для терминала печати технических документаций.
  components:
  - type: Sprite
    sprite: _radiant/Objects/Misc/module.rsi
    state: cpu_acorp
  - type: ComputerBoard
    prototype: ComputerTechnologyDiskTerminalAcorp

- type: entity
  id: MachineFTLDriveCircuitboard
  parent: BaseMachineCircuitboard
  name: плата двигателя БСС
  description: Плата для двигателя блюспейс Скачка
  components:
    - type: Sprite
      state: engineering
    - type: MachineBoard
      prototype: MachineFTLDrive
      componentRequirements:
        AmeFuelContainer:
          amount: 1
          defaultPrototype: AmeJar
      stackRequirements:
        Glass: 10
        Steel: 10