- type: entity
  id: ProtolatheMachineCircuitboardAcorp
  parent: BaseMachineCircuitboard
  name: принтер акорп (машинная плата)
  description: Печатная плата для принтера акорп
  components:
    - type: MachineBoard
      prototype: ProtolatheAcorp
      requirements: # Frontier
        Manipulator: 10 # Frontier stackRequirements<requirements
      tagRequirements:
        GlassBeaker:
          amount: 2
          defaultPrototype: Beaker

- type: entity
  id: MachineFTLDriveCircuitboard
  parent: BaseMachineCircuitboard
  name: плата двигателя БСС
  description: Плата для двигателя блюспейс Скачка
  components:
    - type: Sprite
      state: engineering
    - type: MachineBoard
      prototype: MachineFTLDrive
      componentRequirements:
        AmeFuelContainer:
          amount: 1
          defaultPrototype: AmeJar
      stackRequirements:
        Glass: 10
        Steel: 10