using Content.Shared._radiant.Languages;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._radiant.Languages.UI;

[GenerateTypedNameReferences]
public sealed partial class LanguageTranslatorWindow : DefaultWindow
{
    public LanguageTranslatorWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void Populate(LanguageTranslatorUiState state)
    {
        LanguageLabel.Text = Loc.GetString("paper-ui-language-label", ("language", state.Language));
        TranslatedText.SetMessage(state.Text);
    }
}
