using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Starlight.Medical.Surgery;
// Based on the RMC14.
// https://github.com/RMC-14/RMC-14
[GenerateTypedNameReferences]
public sealed partial class SurgeryWindow : DefaultWindow
{
    public event Action? OnFrameRefresh;

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        OnFrameRefresh?.Invoke();
    }

    public SurgeryWindow()
    {
        RobustXamlLoader.Load(this);
        PartsButton.Text = Loc.GetString("starlight-surgery-ui-parts");
        SurgeriesButton.Text = Loc.GetString("starlight-surgery-ui-surgeries");
        StepsButton.Text = Loc.GetString("starlight-surgery-ui-steps");
    }
}
