using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client._radiant.Casino;

[GenerateTypedNameReferences]
public sealed partial class CasinoMachineWindow : FancyWindow
{
    public CasinoUiFragment Fragment => CasinoFragment;

    public CasinoMachineWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
