using Content.Shared._radiant.Casino;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Prototypes;
using Robust.Shared.Random;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._radiant.Casino;

[GenerateTypedNameReferences]
public sealed partial class CasinoUiFragment : BoxContainer
{
    private readonly SpriteSystem _sprites;
    private readonly IRobustRandom _random;
    private static readonly ResPath CasinoRsi = new("/Textures/_radiant/Interface/Casino/casino.rsi");
    private bool _spinning;
    private CasinoUiState? _pendingState;

    public event Action<int>? OnSpin;

    public CasinoUiFragment()
    {
        _sprites = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<SpriteSystem>();
        _random = IoCManager.Resolve<IRobustRandom>();
        RobustXamlLoader.Load(this);
        SpinButton.OnPressed += _ => SendSpin();
        Bet100Button.OnPressed += _ => BetLine.Text = "100";
        Bet1KButton.OnPressed += _ => BetLine.Text = "1000";
        Bet10KButton.OnPressed += _ => BetLine.Text = "10000";
        Bet100KButton.OnPressed += _ => BetLine.Text = "100000";
        UpdateState(new CasinoUiState(
            0,
            -1,
            5,
            CasinoSymbol.Cherry,
            CasinoSymbol.Clover,
            CasinoSymbol.Seven,
            0,
            CasinoSpinResult.None));
    }

    public void UpdateState(CasinoUiState state)
    {
        if (_spinning)
        {
            _pendingState = state;
            return;
        }

        ApplyState(state);
    }

    private void ApplyState(CasinoUiState state)
    {
        FirstReel.Texture = GetTexture(state.First);
        SecondReel.Texture = GetTexture(state.Second);
        ThirdReel.Texture = GetTexture(state.Third);

        BankBalanceLabel.Text = state.BankBalance >= 0
            ? Loc.GetString("casino-bank-balance", ("amount", state.BankBalance))
            : Loc.GetString("casino-bank-unavailable");

        SpinButton.Text = Loc.GetString("casino-spin");
        SpinButton.Disabled = state.BankBalance < 0;

        ResultLabel.Text = state.Result switch
        {
            CasinoSpinResult.Win => Loc.GetString("casino-result-win", ("amount", state.Payout)),
            CasinoSpinResult.Loss => Loc.GetString("casino-result-loss"),
            CasinoSpinResult.NotEnough => Loc.GetString("casino-result-not-enough"),
            CasinoSpinResult.DepositSuccess => Loc.GetString("casino-result-deposit", ("amount", state.Payout)),
            CasinoSpinResult.WithdrawSuccess => Loc.GetString("casino-result-withdraw", ("amount", state.Payout)),
            CasinoSpinResult.BankInsufficient => Loc.GetString("casino-result-bank-insufficient"),
            CasinoSpinResult.CasinoInsufficient => Loc.GetString("casino-result-casino-insufficient"),
            CasinoSpinResult.InvalidAmount => Loc.GetString("casino-result-invalid-amount"),
            CasinoSpinResult.BankUnavailable => Loc.GetString("casino-result-bank-unavailable"),
            CasinoSpinResult.Cooldown => Loc.GetString("casino-result-cooldown"),
            _ => Loc.GetString("casino-result-ready"),
        };
    }

    private void SendSpin()
    {
        if (!int.TryParse(BetLine.Text, out var bet) || bet <= 0 || bet > 100_000)
        {
            ResultLabel.Text = Loc.GetString("casino-result-invalid-amount");
            return;
        }

        StartSpinAnimation();
        OnSpin?.Invoke(bet);
    }

    private void StartSpinAnimation()
    {
        _spinning = true;
        _pendingState = null;
        SpinButton.Disabled = true;
        ResultLabel.Text = Loc.GetString("casino-result-spinning");

        for (var i = 1; i <= 15; i++)
        {
            Timer.Spawn(i * 100, () =>
            {
                FirstReel.Texture = GetTexture(RandomSymbol());
                SecondReel.Texture = GetTexture(RandomSymbol());
                ThirdReel.Texture = GetTexture(RandomSymbol());
            });
        }

        Timer.Spawn(1600, () =>
        {
            _spinning = false;
            if (_pendingState is { } state)
            {
                _pendingState = null;
                ApplyState(state);
            }
            else
            {
                SpinButton.Disabled = false;
            }
        });
    }

    private CasinoSymbol RandomSymbol()
    {
        return (CasinoSymbol) _random.Next(Enum.GetValues<CasinoSymbol>().Length);
    }

    private Texture GetTexture(CasinoSymbol symbol)
    {
        var name = symbol switch
        {
            CasinoSymbol.Cherry => "cherry",
            CasinoSymbol.Clover => "clover",
            CasinoSymbol.Diamond => "diamond",
            CasinoSymbol.Horseshoe => "horseshoe",
            CasinoSymbol.Lemon => "lemon",
            CasinoSymbol.Plum => "plum",
            CasinoSymbol.Seven => "seven",
            _ => "cherry",
        };

        return _sprites.Frame0(new SpriteSpecifier.Rsi(CasinoRsi, name));
    }
}
