using Content.Client._Goobstation.Languages;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;

namespace Content.Client._Goobstation.Languages.UI;

/// <summary>
/// Radiant Sector: compact in-game language selector inspired by the language menus in upstream builds.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class LanguageMenuWindow : DefaultWindow
{
    private readonly LanguageMenuSystem _languageMenu;
    private string _nativeLanguage = string.Empty;
    private LanguageInfoWindow? _infoWindow;

    public LanguageMenuWindow()
    {
        RobustXamlLoader.Load(this);
        _languageMenu = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<LanguageMenuSystem>();

        CommonButton.OnPressed += _ => _languageMenu.SelectLanguage(false);
        NativeButton.OnPressed += _ => _languageMenu.SelectLanguage(true);
        // Radiant Sector: show help for the language beside the pressed question mark.
        CommonInfoButton.OnPressed += _ => OpenLanguageInfo(false);
        NativeInfoButton.OnPressed += _ => OpenLanguageInfo(true);
    }

    public void UpdateState(string nativeLanguage, bool nativeSelected, bool canUseNative, bool canUseGalactic)
    {
        _nativeLanguage = nativeLanguage;
        CurrentLanguageLabel.Text = nativeSelected || !canUseGalactic
            ? $"Сейчас выбран: {nativeLanguage}"
            : "Сейчас выбран: Общегалактический";

        CommonButton.Text = canUseGalactic
            ? (nativeSelected ? "Выбрать общегалактический" : "Общегалактический ✓")
            : "Общегалактический недоступен";
        CommonButton.Disabled = !canUseGalactic || !nativeSelected;

        NativeButton.Text = canUseNative
            ? (nativeSelected ? $"{nativeLanguage} ✓" : $"Выбрать: {nativeLanguage}")
            : $"{nativeLanguage} недоступен";
        NativeButton.Disabled = !canUseNative || nativeSelected;
        CommonInfoButton.Visible = canUseGalactic;
        NativeInfoButton.Visible = canUseNative;

        _infoWindow?.UpdateLanguage(nativeLanguage, _infoWindow.ShowingNative);
    }

    private void OpenLanguageInfo(bool native)
    {
        if (native && string.IsNullOrEmpty(_nativeLanguage))
            return;

        if (_infoWindow == null)
        {
            _infoWindow = new LanguageInfoWindow();
            _infoWindow.OnClose += () => _infoWindow = null;
            _infoWindow.OpenCentered();
        }

        _infoWindow.UpdateLanguage(_nativeLanguage, native);
    }
}
