using System.Linq;
using System.Numerics;
using Content.Client.UserInterface.Systems.Interaction;
using Content.Shared.Buckle.Components;
using Content.Shared.Chat.Prototypes;
using Content.Shared._radiant;
using Content.Shared.DetailExaminable;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.IdentityManagement;
using Content.Shared.Interaction;
using Content.Shared.Interaction.Panel;
using Content.Shared._radiant.Arousal.Components;
using Content.Shared._radiant.ERP;
using Content.Shared.Mind.Components;
using Content.Shared.Mobs;
using Content.Shared.Mobs.Components;
using Content.Shared.NPC;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Player;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

/// In the name of the Father and the Holy Spirit, have mercy on this panel. Amen
namespace Content.Client.Interaction.Panel.Ui
{
    [GenerateTypedNameReferences]
    public sealed partial class InteractionPanelMenu : DefaultWindow
    {
        [Dependency] private readonly IFileDialogManager _dialogManager = default!;
        [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
        [Dependency] private readonly IEntityManager _entManager = default!;
        [Dependency] private readonly IEntityNetworkManager _entityNetworkManager = default!;
        [Dependency] private readonly IPlayerManager _playerManager = default!;
        [Dependency] private readonly InteractionPanelManager _sharedInteraction = default!;
        private readonly InteractionConstructorUIController _interactionConstructorController;
        private readonly InteractionEditorUIController _interactionEditorController;
        private static List<InteractionPrototype> _importedPrototypes = new(); // Memory
        private static List<BoxContainer> _importedButtons = new(); // Memory
        private static List<BoxContainer> _favoriteButtons = new(); // Memory
        private static List<InteractionPrototype> _favoritePrototypes = new(); // Memory
        private static bool _soloModeEnabled;
        private static bool _hideFromOthersEnabled;
        private List<BoxContainer> _allButtons = new();
        private TransformSystem _transform;
        private EntityLookupSystem _lookup;
        private SharedInteractionSystem _interaction;
        private ISawmill _sawmill = default!;
        private float _updateDif;
        private const float TargetSearchRange = 2f;
        private const float TargetUpdateInterval = 0.25f;

        public BoxContainer UserModel => this.FindControl<BoxContainer>("UserSpriteView");
        public BoxContainer TargetModel => this.FindControl<BoxContainer>("TargetSpriteView");
        public CollapsibleHeading SpecialHeading => this.FindControl<CollapsibleHeading>("Special");
        public CollapsibleHeading FavouritesHeading => this.FindControl<CollapsibleHeading>("Favourites");
        public CollapsibleHeading LipsHeading => this.FindControl<CollapsibleHeading>("Lips");
        public CollapsibleHeading HeadHeading => this.FindControl<CollapsibleHeading>("Head");
        public CollapsibleHeading ChestHeading => this.FindControl<CollapsibleHeading>("Chest");
        public CollapsibleHeading GroinHeading => this.FindControl<CollapsibleHeading>("Groin");
        public CollapsibleHeading TailHeading => this.FindControl<CollapsibleHeading>("Tail");
        public CollapsibleHeading BodyHeading => this.FindControl<CollapsibleHeading>("Body");
        private SpriteView _userSpriteView;
        private SpriteView _targetSpriteView;
        private Label _targetLabel;
        private Label _userGenderLabel;
        private Label _targetGenderLabel;

        public InteractionPanelMenu()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            _interactionConstructorController = UserInterfaceManager.GetUIController<InteractionConstructorUIController>();
            _interactionEditorController = UserInterfaceManager.GetUIController<InteractionEditorUIController>();

            _transform = _entManager.System<TransformSystem>();
            _lookup = _entManager.System<EntityLookupSystem>();
            _interaction = _entManager.System<SharedInteractionSystem>();
            _sawmill = Logger.GetSawmill("interaction_import");

            _userSpriteView = CreateSpriteView();
            UserModel.AddChild(_userSpriteView);

            _targetSpriteView = CreateSpriteView();
            TargetModel.AddChild(_targetSpriteView);

            _targetLabel = CreateLabel();
            _userGenderLabel = CreateLabel();
            _targetGenderLabel = CreateLabel();

            var importButton = FindControl<Button>("ImportButton");
            var constructorButton = FindControl<Button>("ConstructorButton");

            importButton.OnButtonUp += _ => HandleImport();
            constructorButton.OnButtonUp += _ => HandleConstructor();

            SearchBar.OnTextChanged += OnSearchTextChanged;

            SoloModeCheckBox.Pressed = _soloModeEnabled;
            HideFromOthersCheckBox.Pressed = _hideFromOthersEnabled;
            SoloModeCheckBox.OnToggled += _ =>
            {
                _soloModeEnabled = SoloModeCheckBox.Pressed;
                OnSoloModeToggled();
            };
            HideFromOthersCheckBox.OnToggled += _ => _hideFromOthersEnabled = HideFromOthersCheckBox.Pressed;

            InitializeNamesContainer();
            _playerManager.PlayerStatusChanged += OnUserStatusChanged;

            SetupHeading(SpecialHeading);
            SetupHeading(FavouritesHeading);
            SetupHeading(LipsHeading);
            SetupHeading(HeadHeading);
            SetupHeading(ChestHeading);
            SetupHeading(GroinHeading);
            SetupHeading(TailHeading);
            SetupHeading(BodyHeading);

            PopulateInteractions();
            UpdateTarget();
        }

        protected override void FrameUpdate(FrameEventArgs args)
        {
            base.FrameUpdate(args);

            var session = _playerManager.LocalSession;
            if (session?.AttachedEntity is { } user && IsErpDenied(user))
            {
                Close();
                return;
            }

            UpdateArousalBar();

            _updateDif += args.DeltaSeconds;
            if (_updateDif < TargetUpdateInterval)
                return;

            _updateDif -= TargetUpdateInterval;

            // Update panel
            InitializeNamesContainer();
            PopulateInteractions();
            UpdateTarget();
        }

        #region Initialized
        private void InitializeNamesContainer()
        {
            Names.RemoveAllChildren();

            var session = _playerManager.LocalSession;
            if (session?.AttachedEntity.HasValue == true)
            {
                var user = session.AttachedEntity.Value;
                var appearanceComponent = _entManager.GetComponentOrNull<HumanoidAppearanceComponent>(user);

                var label = CreateLabel();
                label.Text = Loc.GetString("interact-player");
                Names.AddChild(label);

                var userGenderIcon = CreateGenderIconButton(appearanceComponent?.Sex);
                if (userGenderIcon != null)
                {
                    userGenderIcon.Orphan();
                    Names.AddChild(userGenderIcon);
                }
            }

            _targetLabel.Orphan();
            Names.AddChild(CreateSpacer());
            Names.AddChild(_targetLabel);
        }

        private void OnUserStatusChanged(object? sender, SessionStatusEventArgs e)
        {
            if (e.Session.AttachedEntity.HasValue)
            {
                UpdateUser(e.Session.AttachedEntity.Value);
                UpdateTarget();
            }
        }

        private TextureButton CreateGenderIconButton(Sex? sex)
        {
            var texturePath = sex switch
            {
                Sex.Male => "/Textures/_radiant/Interface/InteractionPanel/male.png",
                Sex.Female => "/Textures/_radiant/Interface/InteractionPanel/female.png",
                Sex.Unsexed => "/Textures/_radiant/Interface/InteractionPanel/unsexed.png",
                _ => "/Textures/_radiant/Interface/InteractionPanel/unknown.png"
            };

            var textureResource = IoCManager.Resolve<IResourceCache>().GetResource<TextureResource>(new ResPath(texturePath));
            return new TextureButton
            {
                TextureNormal = textureResource.Texture,
                Margin = new Thickness(4),
                Scale = new Vector2(0.5f, 0.5f)
            };
        }

        private SpriteView CreateSpriteView() => new()
        {
            OverrideDirection = Direction.South,
            Scale = new Vector2(2, 2),
            SetSize = new Vector2(64, 64)
        };

        private Label CreateLabel() => new()
        {
            Margin = new Thickness(4)
        };

        private BoxContainer CreateSpacer() => new()
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            MinHeight = 4,
            HorizontalExpand = true,
            Margin = new Thickness(0)
        };

        private void SetupHeading(CollapsibleHeading heading)
        {
            heading.AddStyleClass(ContainerButton.StyleClassButton);
            heading.Label.HorizontalAlignment = HAlignment.Center;
            heading.Label.HorizontalExpand = true;
        }
        #endregion

        #region Methods
        private void UpdateArousalBar()
        {
            var session = _playerManager.LocalSession;
            if (session?.AttachedEntity is not { } uid ||
                !_entManager.TryGetComponent<ArousalComponent>(uid, out var arousal))
            {
                ArousalBar.Visible = false;
                ArousalBar.Value = 0;
                return;
            }

            ArousalBar.Visible = true;
            var frac = arousal.MaxArousal > 0f
                ? Math.Clamp(arousal.CurrentArousal / arousal.MaxArousal, 0f, 1f)
                : 0f;
            ArousalBar.Value = frac;
        }

        /// <summary>
        /// Whoever is reading this, shut the fuck down if there are problems with downloading.
        /// It's not worth it, they'll decide later. BE PATIENT.
        /// </summary>
        private async void HandleImport()
        {
            await using var file = await _dialogManager.OpenFile(new FileDialogFilters(new FileDialogFilters.Group("yml")));

            if (file == null)
                return;

            try
            {
                var prototypes = _sharedInteraction.FromStream(file);
                if (!prototypes.Any())
                    return;

                _importedButtons.Clear();
                _importedPrototypes.Clear();
                SpecialContainer.RemoveAllChildren();

                foreach (var prototype in prototypes)
                {
                    if (prototype is not InteractionPrototype interactionPrototype)
                        continue;

                    if (_allButtons.Any(b => b.Children.OfType<Button>().Any(btn => btn.Name == interactionPrototype.ID)))
                        continue;

                    _importedPrototypes.Add(interactionPrototype);
                }

                PopulateInteractions();
            }
            catch (Exception exc)
            {
                _sawmill.Error($"Error when importing buttons\n{exc.StackTrace}");
            }
        }

        private void HandleConstructor()
        {
            _interactionConstructorController.ToggleWindow(_soloModeEnabled);
        }

        public void HandleAddConstructor(InteractionPrototype prototype)
        {
            _importedPrototypes.Add(prototype);
            PopulateInteractions();
        }

        public void HandleAddEdit(InteractionPrototype prototype)
        {
            var existingPrototype = _importedPrototypes.FirstOrDefault(p => p.ID == prototype.ID);
            if (existingPrototype != null)
            {
                _importedPrototypes.Remove(existingPrototype);
            }

            _importedPrototypes.Add(prototype);
            PopulateInteractions();
        }

        public void HandleDeleteEdit(InteractionPrototype prototype)
        {
            var existingPrototype = _importedPrototypes.FirstOrDefault(p => p.ID == prototype.ID);
            if (existingPrototype != null)
            {
                _importedPrototypes.Remove(existingPrototype);
            }

            if (!_importedPrototypes.Any())
            {
                _importedButtons.Clear();
                _importedPrototypes.Clear();
                SpecialContainer.RemoveAllChildren();
            }

            PopulateInteractions();
        }

        private void OnPinPressed(InteractionPrototype prototype)
        {
            var existingPrototype = _favoritePrototypes.FirstOrDefault(p => p.ID == prototype.ID);
            if (existingPrototype != null)
                return;

            _favoritePrototypes.Add(prototype);
            PopulateInteractions();
        }

        private void OnUnPinPressed(InteractionPrototype prototype)
        {
            _favoritePrototypes.Remove(prototype);
            if (!_favoritePrototypes.Any())
            {
                _favoriteButtons.Clear();
                _favoritePrototypes.Clear();
                FavouritesContainer.RemoveAllChildren();
            }

            PopulateInteractions();
        }

        private void UpdateTarget()
        {
            _targetSpriteView.RemoveAllChildren();

            var session = _playerManager.LocalSession;
            if (session?.AttachedEntity == null) return;

            var user = session.AttachedEntity.Value;
            var target = GetInteractionTarget(user);

            if (target.HasValue)
            {
                _targetSpriteView.SetEntity(target.Value);

                _targetLabel.Text = Identity.Name(target.Value, _entManager, session.AttachedEntity);

                var appearanceComponent = _entManager.GetComponentOrNull<HumanoidAppearanceComponent>(target.Value);
                UpdateGender(target.Value, appearanceComponent, _targetGenderLabel);
            }
            else
            {
                _targetSpriteView.SetEntity(EntityUid.Invalid);
                _targetGenderLabel.Text = "";
                _targetLabel.Text = "";

                _targetGenderLabel.Orphan();
                TargetModel.AddChild(_targetGenderLabel);
            }
        }

        private void UpdateGender(EntityUid entity, HumanoidAppearanceComponent? appearanceComponent, Label genderLabel)
        {
            genderLabel.Orphan();

            if (appearanceComponent == null)
            {
                genderLabel.Text = Loc.GetString("unknown-nearestplayer");
                TargetModel.AddChild(genderLabel);
                return;
            }

            var targetGenderIcon = CreateGenderIconButton(appearanceComponent.Sex);
            if (targetGenderIcon != null)
            {
                targetGenderIcon.Orphan();
                Names.AddChild(targetGenderIcon);
            }
            var dionaSpecies = new ProtoId<SpeciesPrototype>("Diona");
            var arachnidSpecies = new ProtoId<SpeciesPrototype>("Arachnid");
            var voxSpecies = new ProtoId<SpeciesPrototype>("Vox");

            genderLabel.Text = TryBuildAdultAnatomyText(entity, false, out var anatomyText)
                ? anatomyText
                : appearanceComponent.Species switch
            {
                var species when species == dionaSpecies => string.Join("\n", Loc.GetString("diona-leaves"), Loc.GetString("diona-branches")),
                var species when species == arachnidSpecies => Loc.GetString("arachnid-nearestplayer"),
                var species when species == voxSpecies => Loc.GetString("vox-nearestplayer"),
                _ => appearanceComponent.Sex switch
                {
                    Sex.Male => string.Join("\n", Loc.GetString("male-anal"), Loc.GetString("male-dick")),
                    Sex.Female => string.Join("\n", Loc.GetString("female-anal"), Loc.GetString("female-vagine"), Loc.GetString("female-breasts")),
                    Sex.Unsexed => Loc.GetString("unsexed-nearestplayer"),
                    _ => Loc.GetString("unknown-nearestplayer")
                }
            };

            genderLabel.Orphan();
            TargetModel.AddChild(genderLabel);
        }

        public void UpdateUser(EntityUid user)
        {
            _userSpriteView.SetEntity(user);

            var dionaSpecies = new ProtoId<SpeciesPrototype>("Diona");
            var arachnidSpecies = new ProtoId<SpeciesPrototype>("Arachnid");
            var voxSpecies = new ProtoId<SpeciesPrototype>("Vox");
            var appearanceComponent = _entManager.GetComponentOrNull<HumanoidAppearanceComponent>(user);

            // Radiant sector: refresh this text for every anatomy state, not only
            // when HumanoidAppearance is missing.
            _userGenderLabel.Text = TryBuildAdultAnatomyText(user, true, out var anatomyText)
                ? anatomyText
                : appearanceComponent?.Species switch
            {
                var species when species == dionaSpecies => string.Join("\n", Loc.GetString("diona-leaves-player"), Loc.GetString("diona-branches-player")),
                var species when species == arachnidSpecies => Loc.GetString("arachnid-player"),
                var species when species == voxSpecies => Loc.GetString("vox-player"),
                _ => appearanceComponent?.Sex switch
                {
                    Sex.Male => string.Join("\n", Loc.GetString("male-anal-player"), Loc.GetString("male-dick-player")),
                    Sex.Female => string.Join("\n", Loc.GetString("female-anal-player"), Loc.GetString("female-vagine-player"), Loc.GetString("female-breasts-player")),
                    Sex.Unsexed => Loc.GetString("unsexed-player"),
                    _ => Loc.GetString("unknown-player")
                }
            };

            _userGenderLabel.Orphan();
            UserModel.AddChild(_userGenderLabel);
        }

        // Radiant sector: the panel follows surgically installed anatomy instead of immutable profile sex.
        private bool TryBuildAdultAnatomyText(EntityUid entity, bool self, out string text)
        {
            text = string.Empty;
            if (!_entManager.TryGetComponent<AdultAnatomyComponent>(entity, out var anatomy) || !anatomy.AnatomyInitialized)
                return false;

            var suffix = self ? "-player" : string.Empty;
            var parts = new List<string> { Loc.GetString($"adult-anatomy-anal{suffix}") };
            if (anatomy.HasPenis)
            {
                parts.Add(Loc.GetString($"adult-anatomy-penis{suffix}"));
                if (!anatomy.PenisNervesIntact)
                    parts.Add(Loc.GetString($"adult-anatomy-penis-denervated{suffix}"));
            }
            if (anatomy.HasVagina)
                parts.Add(Loc.GetString($"adult-anatomy-vagina{suffix}"));
            if (anatomy.HasBreasts)
                parts.Add(Loc.GetString($"adult-anatomy-breasts{suffix}", ("size", Loc.GetString($"adult-anatomy-size-{anatomy.BreastSize.ToString().ToLowerInvariant()}"))));

            text = string.Join("\n", parts);
            return true;
        }

        private void PopulateInteractions()
        {
            _allButtons.Clear();

            var interactionPrototypes = SortInteractions(_prototypeManager.EnumeratePrototypes<InteractionPrototype>());
            var session = _playerManager.LocalSession;

            if (session?.AttachedEntity == null) return;

            var user = session.AttachedEntity.Value;
            if (IsErpDenied(user))
            {
                Close();
                return;
            }

            if (!_entManager.TryGetComponent<HumanoidAppearanceComponent>(user, out var appearanceComponent)) return;

            var target = GetInteractionTarget(user);
            foreach (var prototype in interactionPrototypes)
            {
                if (prototype.Abstract)
                    continue;

                if (!IsInteractionVisible(prototype, appearanceComponent, target))
                    continue;

                if (_importedButtons.Any(b => b.Children.OfType<Button>().Any(btn => btn.Name == prototype.ID)))
                    continue;

                var buttonContainer = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Horizontal,
                    HorizontalExpand = false,
                    Margin = new Thickness(0.1f)
                };

                var button = new Button
                {
                    Text = Loc.GetString(prototype.Name),
                    Name = prototype.ID,
                    MinWidth = 360,
                    MinHeight = 32
                };

                var pinButton = new Button
                {
                    Text = Loc.GetString("interaction-panel-pin"),
                    MinWidth = 52,
                    MinHeight = 32
                };

                button.OnButtonDown += args => OnInteractionPressed(prototype.ID);
                pinButton.OnButtonDown += args => OnPinPressed(prototype);

                if (!string.IsNullOrEmpty(prototype.Icon))
                {
                    var texturePath = new ResPath(prototype.Icon.StartsWith("/") ? prototype.Icon : $"/Textures/{prototype.Icon}");
                    var textureResource = IoCManager.Resolve<IResourceCache>().GetResource<TextureResource>(texturePath);

                    var iconButton = new TextureButton
                    {
                        TextureNormal = textureResource.Texture,
                        Margin = new Thickness(4),
                        Scale = new Vector2(1f, 1f)
                    };

                    buttonContainer.AddChild(iconButton);
                }

                buttonContainer.AddChild(button);
                buttonContainer.AddChild(pinButton);
                _allButtons.Add(buttonContainer);

                GetContainerByCategory(prototype).AddChild(buttonContainer);
            }

            if (_importedPrototypes.Any())
            {
                _importedButtons.Clear();

                foreach (var interactionPrototype in SortInteractions(_importedPrototypes))
                {
                    if (!IsInteractionVisible(interactionPrototype, appearanceComponent, target))
                        continue;

                    if (_importedButtons.Any(b => b.Children.OfType<Button>().Any(btn => btn.Name == interactionPrototype.ID)))
                        continue;

                    var buttonContainer = new BoxContainer
                    {
                        Orientation = BoxContainer.LayoutOrientation.Horizontal,
                        HorizontalExpand = false,
                        Margin = new Thickness(0.1f)
                    };

                    var button = new Button
                    {
                        Text = Loc.GetString(interactionPrototype.Name),
                        Name = interactionPrototype.ID,
                        MinWidth = 360,
                        MinHeight = 32
                    };

                    var editorButton = new Button
                    {
                        Text = Loc.GetString("interaction-panel-editor"),
                        MinWidth = 52,
                        MinHeight = 32
                    };

                    button.OnButtonDown += args => OnInteractionPressed(interactionPrototype.ID, interactionPrototype);
                    editorButton.OnButtonDown += args => OnEditorPressed(interactionPrototype);

                    if (!string.IsNullOrEmpty(interactionPrototype.Icon))
                    {
                        var texturePath = new ResPath(interactionPrototype.Icon.StartsWith("/") ? interactionPrototype.Icon : $"/Textures/{interactionPrototype.Icon}");
                        var textureResource = IoCManager.Resolve<IResourceCache>().GetResource<TextureResource>(texturePath);

                        var iconButton = new TextureButton
                        {
                            TextureNormal = textureResource.Texture,
                            Margin = new Thickness(4),
                            Scale = new Vector2(1f, 1f)
                        };

                        buttonContainer.AddChild(iconButton);
                    }

                    buttonContainer.AddChild(button);
                    buttonContainer.AddChild(editorButton);
                    _importedButtons.Add(buttonContainer);
                    SpecialContainer.AddChild(buttonContainer);
                }
            }

            if (_favoritePrototypes.Any())
            {
                _favoriteButtons.Clear();

                foreach (var interactionPrototype in SortInteractions(_favoritePrototypes))
                {
                    if (!IsInteractionVisible(interactionPrototype, appearanceComponent, target))
                        continue;

                    if (_favoriteButtons.Any(b => b.Children.OfType<Button>().Any(btn => btn.Name == interactionPrototype.ID)))
                        continue;

                    var buttonContainer = new BoxContainer
                    {
                        Orientation = BoxContainer.LayoutOrientation.Horizontal,
                        HorizontalExpand = false,
                        Margin = new Thickness(0.1f)
                    };

                    var button = new Button
                    {
                        Text = Loc.GetString(interactionPrototype.Name),
                        Name = interactionPrototype.ID,
                        MinWidth = 360,
                        MinHeight = 32
                    };

                    var unPinButton = new Button
                    {
                        Text = Loc.GetString("interaction-panel-unpin"),
                        MinWidth = 52,
                        MinHeight = 32
                    };

                    button.OnButtonDown += args => OnInteractionPressed(interactionPrototype.ID);
                    unPinButton.OnButtonDown += args => OnUnPinPressed(interactionPrototype);

                    if (!string.IsNullOrEmpty(interactionPrototype.Icon))
                    {
                        var texturePath = new ResPath(interactionPrototype.Icon.StartsWith("/") ? interactionPrototype.Icon : $"/Textures/{interactionPrototype.Icon}");
                        var textureResource = IoCManager.Resolve<IResourceCache>().GetResource<TextureResource>(texturePath);

                        var iconButton = new TextureButton
                        {
                            TextureNormal = textureResource.Texture,
                            Margin = new Thickness(4),
                            Scale = new Vector2(1f, 1f)
                        };

                        buttonContainer.AddChild(iconButton);
                    }

                    buttonContainer.AddChild(button);
                    buttonContainer.AddChild(unPinButton);
                    _favoriteButtons.Add(buttonContainer);
                    FavouritesContainer.AddChild(buttonContainer);
                }
            }

            UpdateButtonsVisibility();
        }

        private void OnSearchTextChanged(LineEdit.LineEditEventArgs args)
        {
            UpdateButtonsVisibility();
        }

        private void UpdateButtonsVisibility()
        {
            var searchText = SearchBar.Text.ToLower();

            SpecialContainer.RemoveAllChildren();
            FavouritesContainer.RemoveAllChildren();
            LipsContainer.RemoveAllChildren();
            HeadContainer.RemoveAllChildren();
            ChestContainer.RemoveAllChildren();
            GroinContainer.RemoveAllChildren();
            TailContainer.RemoveAllChildren();
            BodyContainer.RemoveAllChildren();

            foreach (var buttonContainer in _allButtons)
            {
                var button = buttonContainer.Children.OfType<Button>().FirstOrDefault();
                if (button == null || string.IsNullOrEmpty(button.Name)) continue;

                bool isVisible = string.IsNullOrEmpty(searchText) || button.Text?.ToLower().Contains(searchText) == true;

                if (isVisible)
                {
                    var prototype = _prototypeManager.Index<InteractionPrototype>(button.Name);
                    if (prototype == null) continue;

                    GetContainerByCategory(prototype).AddChild(buttonContainer);
                }
            }

            foreach (var buttonContainer in _importedButtons)
            {
                var button = buttonContainer.Children.OfType<Button>().FirstOrDefault();
                if (button == null || string.IsNullOrEmpty(button.Name)) continue;

                bool isVisible = string.IsNullOrEmpty(searchText) || button.Text?.ToLower().Contains(searchText) == true;

                if (isVisible)
                {
                    SpecialContainer.AddChild(buttonContainer);
                }
            }

            foreach (var buttonContainer in _favoriteButtons)
            {
                var button = buttonContainer.Children.OfType<Button>().FirstOrDefault();
                if (button == null || string.IsNullOrEmpty(button.Name)) continue;

                bool isVisible = string.IsNullOrEmpty(searchText) || button.Text?.ToLower().Contains(searchText) == true;

                if (isVisible)
                {
                    FavouritesContainer.AddChild(buttonContainer);
                }
            }
        }

        private void OnSoloModeToggled()
        {
            PopulateInteractions();
            UpdateTarget();
        }

        private EntityUid? GetInteractionTarget(EntityUid user)
        {
            if (SoloModeCheckBox.Pressed)
                return null;

            return FindTarget(user);
        }

        private EntityUid? FindTarget(EntityUid user)
        {
            if (!_entManager.TryGetComponent<TransformComponent>(user, out var sourceTransform))
                return null;

            EntityUid? bestTarget = null;
            var bestDistance = float.MaxValue;

            void Consider(EntityUid candidate)
            {
                if (candidate == user || !IsValidInteractionTarget(candidate))
                    return;

                if (!_interaction.InRangeUnobstructed(user, candidate, range: TargetSearchRange, popup: false))
                    return;

                var distance = (_transform.GetWorldPosition(user) - _transform.GetWorldPosition(candidate)).LengthSquared();
                if (distance >= bestDistance)
                    return;

                bestDistance = distance;
                bestTarget = candidate;
            }

            foreach (var entity in _lookup.GetEntitiesInRange<HumanoidAppearanceComponent>(sourceTransform.Coordinates, TargetSearchRange))
                Consider(entity.Owner);

            foreach (var strapEntity in _lookup.GetEntitiesInRange<StrapComponent>(sourceTransform.Coordinates, TargetSearchRange))
            {
                if (!_entManager.TryGetComponent<StrapComponent>(strapEntity.Owner, out var strapComponent))
                    continue;

                foreach (var buckledEntity in strapComponent.BuckledEntities)
                    Consider(buckledEntity);
            }

            return bestTarget;
        }

        private bool IsValidInteractionTarget(EntityUid entity)
        {
            if (!_entManager.HasComponent<HumanoidAppearanceComponent>(entity) || IsErpDenied(entity))
                return false;

            if (!IsPlayerTarget(entity))
                return false;

            if (_entManager.TryGetComponent<MobThresholdsComponent>(entity, out var thresholds) &&
                thresholds.CurrentThresholdState != MobState.Alive &&
                thresholds.CurrentThresholdState != MobState.Invalid)
                return false;

            return true;
        }

        private bool IsPlayerTarget(EntityUid entity)
        {
            foreach (var session in _playerManager.Sessions)
            {
                if (session.AttachedEntity == entity)
                    return true;
            }

            return _entManager.TryGetComponent<MindContainerComponent>(entity, out var mindContainer)
                   && mindContainer.HasMind
                   && !_entManager.HasComponent<ActiveNPCComponent>(entity);
        }

        private bool IsErpDenied(EntityUid uid)
        {
            return _entManager.TryGetComponent<DetailExaminableComponent>(uid, out var detail) &&
                   detail.ERPStatus == EnumERPStatus.NO;
        }
        #endregion

        private static IEnumerable<InteractionPrototype> SortInteractions(IEnumerable<InteractionPrototype> prototypes)
        {
            var list = prototypes.ToList();
            list.Sort((a, b) =>
            {
                var solo = a.Solo.CompareTo(b.Solo);
                if (solo != 0)
                    return solo;

                var erp = a.ERP.CompareTo(b.ERP);
                if (erp != 0)
                    return erp;

                var name = string.Compare(
                    Loc.GetString(a.Name),
                    Loc.GetString(b.Name),
                    StringComparison.CurrentCultureIgnoreCase);
                if (name != 0)
                    return name;

                return string.Compare(a.ID, b.ID, StringComparison.Ordinal);
            });

            return list;
        }

        private BoxContainer GetContainerByCategory(InteractionPrototype prototype)
        {
            return prototype.Category.ToLowerInvariant() switch
            {
                "lips" or "lip" or "губы" => LipsContainer,
                "head" or "голова" => HeadContainer,
                "chest" or "breasts" or "грудь" => ChestContainer,
                "groin" or "genitals" or "промежность" => GroinContainer,
                "tail" or "хвост" => TailContainer,
                "body" or "тело" => BodyContainer,
                _ => BodyContainer
            };
        }

        #region Logic
        private bool IsInteractionAllowed(InteractionPrototype prototype, HumanoidAppearanceComponent userAppearance, EntityUid target)
        {
            if (!_entManager.TryGetComponent<HumanoidAppearanceComponent>(target, out var targetAppearance))
                return false;

            bool isSpeciesAllowed = prototype.AllowedSpecies?.Contains("all") == true || prototype.AllowedSpecies?.Contains(userAppearance.Species) == true;
            bool isSpeciesBlacklisted = prototype.BlackListSpecies?.Contains(userAppearance.Species) == true || prototype.BlackListSpecies?.Contains(targetAppearance.Species) == true;
            bool isGenderAllowed = IsUserAnatomyAllowed(prototype, userAppearance);
            bool isNearestSpeciesAllowed = prototype.NearestAllowedSpecies?.Contains("all") == true || prototype.NearestAllowedSpecies?.Contains(targetAppearance.Species) == true;
            bool isNearestGenderAllowed = IsTargetAnatomyAllowed(prototype, targetAppearance, target);
            bool isTargetEntityAllowed = prototype.TargetEntityId == null || prototype.TargetEntityId.Contains(target.ToString());


            return isSpeciesAllowed && !isSpeciesBlacklisted && isGenderAllowed && isNearestSpeciesAllowed && isNearestGenderAllowed && isTargetEntityAllowed;
        }

        private bool IsInteractionVisible(InteractionPrototype prototype, HumanoidAppearanceComponent userAppearance, EntityUid? target)
        {
            if (target == null)
                return prototype.Solo && IsSoloInteractionAllowed(prototype, userAppearance);

            return !prototype.Solo && IsInteractionAllowed(prototype, userAppearance, target.Value);
        }

        private bool IsSoloInteractionAllowed(InteractionPrototype prototype, HumanoidAppearanceComponent userAppearance)
        {
            var isSpeciesAllowed = prototype.AllowedSpecies?.Contains("all") == true || prototype.AllowedSpecies?.Contains(userAppearance.Species) == true;
            var isSpeciesBlacklisted = prototype.BlackListSpecies?.Contains(userAppearance.Species) == true;
            var isGenderAllowed = IsUserAnatomyAllowed(prototype, userAppearance);

            return isSpeciesAllowed && !isSpeciesBlacklisted && isGenderAllowed;
        }

        private bool IsUserAnatomyAllowed(InteractionPrototype prototype, HumanoidAppearanceComponent appearance)
        {
            var genders = prototype.AllowedGenders;
            if (genders?.Contains("all") == true)
                return true;
            var uid = _playerManager.LocalSession?.AttachedEntity;
            if (uid == null || !_entManager.TryGetComponent<AdultAnatomyComponent>(uid.Value, out var anatomy))
                return genders?.Contains(appearance.Sex.ToString()) == true;
            if (genders?.Contains("Male") == true && anatomy.HasPenis)
                return true;
            if (genders?.Contains("Female") == true)
                return prototype.Category.Equals("chest", StringComparison.OrdinalIgnoreCase)
                    ? anatomy.HasBreasts
                    : anatomy.HasVagina;
            return false;
        }

        private bool IsTargetAnatomyAllowed(InteractionPrototype prototype, HumanoidAppearanceComponent appearance, EntityUid uid)
        {
            var genders = prototype.NearestAllowedGenders;
            if (genders?.Contains("all") == true)
                return true;
            if (!_entManager.TryGetComponent<AdultAnatomyComponent>(uid, out var anatomy))
                return genders?.Contains(appearance.Sex.ToString()) == true;
            if (genders?.Contains("Male") == true && anatomy.HasPenis)
                return true;
            if (genders?.Contains("Female") == true)
                return prototype.Category.Equals("chest", StringComparison.OrdinalIgnoreCase)
                    ? anatomy.HasBreasts
                    : anatomy.HasVagina;
            return false;
        }

        private void OnInteractionPressed(string interactionId)
        {
            var session = _playerManager.LocalSession;
            if (session?.AttachedEntity == null) return;

            var user = session.AttachedEntity.Value;
            if (!_entManager.TryGetNetEntity(user, out var userEntity)) return;

            var target = GetInteractionTarget(user);
            if (target == null &&
                (!_prototypeManager.TryIndex<InteractionPrototype>(interactionId, out var indexed) || !indexed.Solo))
            {
                return;
            }

            var hideFromOthers = HideFromOthersCheckBox.Pressed;
            var hint = GetLocalArousalHint(interactionId, null);
            NetEntity? targetNetEntity = null;
            if (target != null)
                targetNetEntity = _entManager.GetNetEntity(target.Value);

            _entityNetworkManager.SendSystemNetworkMessage(new InteractionPressedEvent(userEntity.Value, interactionId, targetNetEntity, null, hideFromOthers, hint));
        }

        private void OnInteractionPressed(string interactionId, InteractionPrototype prototype)
        {
            var session = _playerManager.LocalSession;
            if (session?.AttachedEntity == null) return;

            var user = session.AttachedEntity.Value;
            if (!_entManager.TryGetNetEntity(user, out var userEntity)) return;

            var target = GetInteractionTarget(user);
            if (target == null && !prototype.Solo)
                return;

            var hideFromOthers = HideFromOthersCheckBox.Pressed;
            var hint = GetLocalArousalHint(interactionId, prototype);
            NetEntity? targetNetEntity = null;
            if (target != null)
                targetNetEntity = _entManager.GetNetEntity(target.Value);

            _entityNetworkManager.SendSystemNetworkMessage(new InteractionPressedEvent(userEntity.Value, interactionId, targetNetEntity, prototype, hideFromOthers, hint));
        }

        private int GetLocalArousalHint(string interactionId, InteractionPrototype? imported)
        {
            if (_prototypeManager.TryIndex<InteractionPrototype>(interactionId, out var indexed))
                return indexed.EffectiveArousal;
            return imported?.EffectiveArousal ?? 0;
        }

        private void OnEditorPressed(InteractionPrototype prototype)
        {
            _interactionEditorController.ToggleWindow(prototype);
        }
        #endregion
    }
}
