using System.Linq;
using System.IO;
using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Timing;
using Content.Shared.CartridgeLoader.Cartridges;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class MessengerUiFragment : BoxContainer
{
    private MessengerUiState? _state;
    private int _currentPartnerId;
    private int _expandedFriendId;
    private bool _creatingGroup;
    private string _groupName = string.Empty;
    private string _discoverSearch = string.Empty;
    private bool _choosingProfilePhoto;
    private bool _choosingChatPhoto;
    private int _cameraPhotoCount;
    private List<byte[]> _cameraPhotos = [];
    private readonly HashSet<int> _selectedGroupMembers = new();
    private int _scrollChatFramesRemaining;
    private int _chatPartnerId;
    private int _chatMessageCount = -1;

    public event Action<MessengerUiAction, int, string?, List<int>?>? OnAction;
    // Radiant Sector: keeps photo-library indices separate from text message data.
    public event Action<MessengerUiAction, int, int>? OnPhotoAction;

    public MessengerUiFragment()
    {
        RobustXamlLoader.Load(this);
        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;

        FriendsTabButton.OnPressed += _ => ShowFriends();
        DialogsTabButton.OnPressed += _ => ShowDialogs();
        BackButton.OnPressed += _ => ShowDialogs();
        ContactExchangeButton.OnPressed += _ => OnAction?.Invoke(MessengerUiAction.Refresh, 0, null, null);
        ProfileButton.OnPressed += _ =>
        {
            _creatingGroup = false;
            if (_cameraPhotoCount == 0)
            {
                // Radiant Sector: with an empty gallery, go directly to the camera instead of an empty picker.
                OnAction?.Invoke(MessengerUiAction.CaptureProfilePhoto, 0, null, null);
                return;
            }

            _choosingProfilePhoto = true;
            ShowFriends();
        };
        NotificationsButton.OnPressed += _ => OnAction?.Invoke(MessengerUiAction.ToggleNotifications, 0, null, null);
        DiscoverSearch.OnTextChanged += args => OnDiscoverSearchChanged(args.Text);
        CreateGroupButton.OnPressed += _ =>
        {
            _creatingGroup = true;
            ShowFriends();
            if (_state == null)
            {
                FriendsContainer.RemoveAllChildren();
                FriendsContainer.AddChild(CreateGroupCreator());
            }
            else
            {
                BuildLists();
            }
        };
        SendButton.OnPressed += _ => SendMessage();
        PhotoButton.OnPressed += _ =>
        {
            if (_currentPartnerId == 0)
                return;

            _choosingChatPhoto = true;
            BuildChat();
        };
        MessageInput.OnTextEntered += _ => SendMessage();
        ShowFriends();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_scrollChatFramesRemaining <= 0)
            return;

        MessagesScroll.VScrollTarget = float.MaxValue;
        _scrollChatFramesRemaining--;
    }

    public void UpdateState(MessengerUiState state)
    {
        _state = state;
        _cameraPhotoCount = state.CameraPhotoCount;
        _cameraPhotos = state.CameraPhotos;
        NotificationsButton.Text = Loc.GetString(state.NotificationsEnabled ? "messenger-notifications-on" : "messenger-notifications-off");

        if (!_creatingGroup && ShouldRebuildLists())
            BuildLists();

        if (ChatPage.Visible && _currentPartnerId != 0)
        {
            var messages = GetCurrentChatMessages().ToList();
            if (_currentPartnerId != _chatPartnerId || messages.Count != _chatMessageCount)
            {
                var scrollToBottom = _currentPartnerId != _chatPartnerId || messages.Count > _chatMessageCount;
                _chatPartnerId = _currentPartnerId;
                _chatMessageCount = messages.Count;
                BuildChat(scrollToBottom);
            }
        }
    }

    private bool ShouldRebuildLists() =>
        FriendsView.Visible || (DialogsView.Visible && DialogsListPage.Visible);

    private void ShowFriends()
    {
        _currentPartnerId = 0;
        FriendsView.Visible = true;
        DialogsView.Visible = false;
        FriendsTabButton.Disabled = true;
        DialogsTabButton.Disabled = false;
        ResetScroll(FriendsScroll);
        BuildLists();
    }

    private void ShowDialogs()
    {
        _currentPartnerId = 0;
        FriendsView.Visible = false;
        DialogsView.Visible = true;
        DialogsListPage.Visible = true;
        ChatPage.Visible = false;
        FriendsTabButton.Disabled = false;
        DialogsTabButton.Disabled = true;
        ResetScroll(DialogsScroll);
        BuildLists();
    }

    private void OnDiscoverSearchChanged(string text)
    {
        _discoverSearch = text.Trim();
        BuildDiscoverList();
        ResetScroll(FriendsScroll);
    }

    private void BuildLists()
    {
        if (_state == null)
            return;

        FriendsContainer.RemoveAllChildren();
        DialogsContainer.RemoveAllChildren();
        RequestsContainer.RemoveAllChildren();

        if (_choosingProfilePhoto)
        {
            FriendsContainer.AddChild(CreateProfilePhotoPicker());
            EmptyContactsLabel.Visible = false;
            RequestsSection.Visible = false;
            DiscoverSection.Visible = false;
            return;
        }

        DiscoverSection.Visible = true;
        if (_creatingGroup)
            FriendsContainer.AddChild(CreateGroupCreator());

        foreach (var contact in _state.Contacts)
        {
            FriendsContainer.AddChild(CreateFriendCard(contact));
            DialogsContainer.AddChild(CreateDialogCard(contact));
        }

        foreach (var group in _state.Groups)
            DialogsContainer.AddChild(CreateGroupCard(group));

        foreach (var request in _state.IncomingRequests)
            RequestsContainer.AddChild(CreateRequestCard(request));

        BuildDiscoverList();

        EmptyContactsLabel.Visible = _state.Contacts.Count == 0 && !_creatingGroup;
        EmptyDialogsLabel.Visible = _state.Contacts.Count == 0 && _state.Groups.Count == 0;
        RequestsSection.Visible = _state.IncomingRequests.Count > 0;
    }

    private void BuildDiscoverList()
    {
        DiscoverContainer.RemoveAllChildren();

        if (_state == null)
            return;

        var users = string.IsNullOrEmpty(_discoverSearch)
            ? _state.AvailableUsers
            : _state.AvailableUsers
                .Where(user => user.Name.Contains(_discoverSearch, StringComparison.OrdinalIgnoreCase))
                .ToList();

        foreach (var user in users)
            DiscoverContainer.AddChild(CreateDiscoverCard(user));

        EmptyDiscoverLabel.Visible = users.Count == 0;
    }

    private Control CreateFriendCard(MessengerContactEntry friend)
    {
        var card = CreateCard("#202C39", "#31465A");
        var contents = new BoxContainer { Orientation = LayoutOrientation.Vertical, HorizontalExpand = true };
        var select = new Button { HorizontalExpand = true };
        var row = new BoxContainer { Orientation = LayoutOrientation.Horizontal, HorizontalExpand = true, Margin = new Thickness(6, 5) };
        row.AddChild(CreateAvatar(friend.Name, "#527DA3", friend.ProfilePhoto));
        row.AddChild(new Label { Text = friend.Name, HorizontalExpand = true, VerticalAlignment = VAlignment.Center, Margin = new Thickness(8, 0), ClipText = true });
        select.AddChild(row);
        select.OnPressed += _ =>
        {
            _expandedFriendId = _expandedFriendId == friend.Id ? 0 : friend.Id;
            BuildLists();
        };
        contents.AddChild(select);

        if (_expandedFriendId == friend.Id)
        {
            var actions = new BoxContainer { Orientation = LayoutOrientation.Horizontal, HorizontalAlignment = HAlignment.Right, Margin = new Thickness(6, 0, 6, 5) };
            var message = new Button { Text = Loc.GetString("messenger-open-chat"), MinWidth = 100 };
            message.OnPressed += _ => OpenChat(friend.Id, friend.Name);
            var remove = new Button { Text = Loc.GetString("messenger-remove-friend"), MinWidth = 80, Margin = new Thickness(4, 0, 0, 0) };
            remove.OnPressed += _ => OnAction?.Invoke(MessengerUiAction.RemoveContact, friend.Id, null, null);
            actions.AddChild(message);
            actions.AddChild(remove);
            contents.AddChild(actions);
        }

        card.AddChild(contents);
        return card;
    }

    private Control CreateDialogCard(MessengerContactEntry contact)
    {
        var card = CreateCard("#202C39", "#31465A");
        var button = new Button { HorizontalExpand = true };
        var row = new BoxContainer { Orientation = LayoutOrientation.Horizontal, HorizontalExpand = true, Margin = new Thickness(6, 5) };
        row.AddChild(CreateAvatar(contact.Name, "#527DA3", contact.ProfilePhoto));
        var details = new BoxContainer { Orientation = LayoutOrientation.Vertical, HorizontalExpand = true, Margin = new Thickness(8, 0) };
        details.AddChild(new Label { Text = contact.Name, HorizontalExpand = true, ClipText = true });
        var last = _state?.Messages
            .Where(m => m.GroupId == 0 && (m.SenderId == contact.Id || m.ReceiverId == contact.Id))
            .OrderByDescending(m => m.Timestamp)
            .FirstOrDefault();
        details.AddChild(new Label { Text = last?.Content ?? Loc.GetString("messenger-no-messages"), FontColorOverride = Color.FromHex("#9EB1C0"), HorizontalExpand = true, ClipText = true });
        row.AddChild(details);
        if (contact.UnreadCount > 0)
            row.AddChild(CreateUnreadBadge(contact.UnreadCount));
        button.AddChild(row);
        button.OnPressed += _ => OpenChat(contact.Id, contact.Name);
        card.AddChild(button);
        return card;
    }

    private Control CreateGroupCard(MessengerGroupEntry group)
    {
        var card = CreateCard("#293B54", "#58769A");
        var button = new Button { Text = "# " + group.Name, HorizontalExpand = true };
        button.OnPressed += _ => OpenChat(-group.Id, group.Name);
        card.AddChild(button);
        return card;
    }

    private Control CreateGroupCreator()
    {
        var card = CreateCard("#27394A", "#5B8CB4");
        var box = new BoxContainer { Orientation = LayoutOrientation.Vertical, HorizontalExpand = true, Margin = new Thickness(6) };
        box.AddChild(new Label { Text = Loc.GetString("messenger-group-title") });
        var name = new LineEdit { Text = _groupName, PlaceHolder = Loc.GetString("messenger-group-name") };
        name.OnTextChanged += _ => _groupName = name.Text;
        box.AddChild(name);
        foreach (var contact in _state?.Contacts ?? [])
        {
            var check = new CheckBox { Text = contact.Name, Pressed = _selectedGroupMembers.Contains(contact.Id) };
            check.OnToggled += args => { if (args.Pressed) _selectedGroupMembers.Add(contact.Id); else _selectedGroupMembers.Remove(contact.Id); };
            box.AddChild(check);
        }
        var create = new Button { Text = Loc.GetString("messenger-create-group") };
        create.OnPressed += _ =>
        {
            OnAction?.Invoke(MessengerUiAction.CreateGroup, 0, _groupName, _selectedGroupMembers.ToList());
            _creatingGroup = false;
            _groupName = string.Empty;
            _selectedGroupMembers.Clear();
        };
        box.AddChild(create);
        card.AddChild(box);
        return card;
    }

    private Control CreateProfilePhotoPicker()
    {
        var card = CreateCard("#27394A", "#5B8CB4");
        var box = new BoxContainer { Orientation = LayoutOrientation.Vertical, HorizontalExpand = true, Margin = new Thickness(6) };
        box.AddChild(new Label { Text = Loc.GetString("messenger-profile-photo") });

        for (var i = 0; i < _cameraPhotos.Count; i++)
        {
            var photoIndex = i;
            var select = CreatePhotoPickerButton(i);
            select.OnPressed += _ =>
            {
                OnAction?.Invoke(MessengerUiAction.SelectProfilePhoto, photoIndex, null, null);
                _choosingProfilePhoto = false;
                BuildLists();
            };
            box.AddChild(select);
        }

        var capture = new Button { Text = Loc.GetString("messenger-profile-photo-capture"), MinHeight = 40 };
        capture.OnPressed += _ => OnAction?.Invoke(MessengerUiAction.CaptureProfilePhoto, 0, null, null);
        box.AddChild(capture);
        var remove = new Button { Text = Loc.GetString("messenger-profile-photo-remove"), MinHeight = 32, Margin = new Thickness(0, 4, 0, 0) };
        remove.OnPressed += _ =>
        {
            OnAction?.Invoke(MessengerUiAction.RemoveProfilePhoto, 0, null, null);
            _choosingProfilePhoto = false;
            BuildLists();
        };
        box.AddChild(remove);
        // Radiant Sector: the picker contents must be attached to its card before it enters the scroll view.
        card.AddChild(box);
        return card;
    }

    private Control CreateRequestCard(MessengerContactEntry request)
    {
        var card = CreateCard("#2B3544", "#536B83");
        var row = new BoxContainer { Orientation = LayoutOrientation.Horizontal, HorizontalExpand = true, Margin = new Thickness(6, 5) };
        row.AddChild(CreateAvatar(request.Name, "#8067A5", request.ProfilePhoto));
        row.AddChild(new Label { Text = request.Name, HorizontalExpand = true, VerticalAlignment = VAlignment.Center, Margin = new Thickness(8, 0), ClipText = true });
        var accept = new Button { Text = Loc.GetString("messenger-accept"), MinWidth = 70 };
        accept.OnPressed += _ => OnAction?.Invoke(MessengerUiAction.AcceptContact, request.Id, null, null);
        var decline = new Button { Text = Loc.GetString("messenger-decline"), MinWidth = 70, Margin = new Thickness(4, 0, 0, 0) };
        decline.OnPressed += _ => OnAction?.Invoke(MessengerUiAction.DeclineContact, request.Id, null, null);
        row.AddChild(accept);
        row.AddChild(decline);
        card.AddChild(row);
        return card;
    }

    private Control CreateDiscoverCard(MessengerContactEntry user)
    {
        var card = CreateCard("#202C39", "#31465A");
        var row = new BoxContainer { Orientation = LayoutOrientation.Horizontal, HorizontalExpand = true, Margin = new Thickness(6, 5) };
        row.AddChild(CreateAvatar(user.Name, "#467D75", user.ProfilePhoto));
        var details = new BoxContainer { Orientation = LayoutOrientation.Vertical, HorizontalExpand = true, Margin = new Thickness(8, 0) };
        details.AddChild(new Label { Text = user.Name, HorizontalExpand = true, ClipText = true });
        row.AddChild(details);
        var add = new Button { Text = Loc.GetString("messenger-add-contact"), MinWidth = 105 };
        add.OnPressed += _ => OnAction?.Invoke(MessengerUiAction.RequestContact, user.Id, null, null);
        row.AddChild(add);
        card.AddChild(row);
        return card;
    }

    private void OpenChat(int partnerId, string name)
    {
        _creatingGroup = false;
        _choosingChatPhoto = false;
        _currentPartnerId = partnerId;
        PartnerLabel.Text = name;
        // Radiant Sector: direct-dialog headers show the contact's selected profile photo.
        var profilePhoto = partnerId > 0
            ? _state?.Contacts.FirstOrDefault(contact => contact.Id == partnerId)?.ProfilePhoto
            : null;
        SetPartnerAvatar(name, profilePhoto);
        PartnerTypeLabel.Text = Loc.GetString(partnerId < 0 ? "messenger-group" : "messenger-contact");
        FriendsView.Visible = false;
        DialogsView.Visible = true;
        DialogsListPage.Visible = false;
        ChatPage.Visible = true;
        FriendsTabButton.Disabled = false;
        DialogsTabButton.Disabled = true;
        OnAction?.Invoke(MessengerUiAction.ReadChat, partnerId, null, null);
        _chatPartnerId = 0;
        _chatMessageCount = -1;
        BuildChat(scrollToBottom: true);
    }

    private void SetPartnerAvatar(string name, byte[]? profilePhoto)
    {
        PartnerInitial.Text = string.IsNullOrWhiteSpace(name) ? "?" : name[..1].ToUpperInvariant();
        PartnerInitial.Visible = true;
        PartnerPhoto.Visible = false;
        PartnerPhoto.Texture = null;

        if (profilePhoto == null || profilePhoto.Length == 0)
            return;

        try
        {
            PartnerPhoto.Texture = LoadAvatarTexture(profilePhoto);
            PartnerPhoto.Visible = true;
            PartnerInitial.Visible = false;
        }
        catch
        {
            // Radiant Sector: invalid or old avatar data falls back to the contact initial.
        }
    }

    private IEnumerable<MessengerMessageEntry> GetCurrentChatMessages()
    {
        if (_state == null || _currentPartnerId == 0)
            return [];

        return _currentPartnerId < 0
            ? _state.Messages.Where(message => message.GroupId == -_currentPartnerId)
            : _state.Messages.Where(message =>
                message.GroupId == 0 &&
                (message.SenderId == _currentPartnerId || message.ReceiverId == _currentPartnerId));
    }

    private void BuildChat(bool scrollToBottom = false)
    {
        if (_state == null || _currentPartnerId == 0)
            return;

        var scrollPosition = MessagesScroll.GetScrollValue();
        MessagesContainer.RemoveAllChildren();
        if (_choosingChatPhoto)
        {
            MessagesContainer.AddChild(CreateChatPhotoPicker());
            return;
        }
        var messages = GetCurrentChatMessages();

        var isGroupChat = _currentPartnerId < 0;
        foreach (var message in messages.OrderBy(message => message.Timestamp))
        {
            var isOwnMessage = message.SenderId == _state.OwnerId;
            var incoming = isGroupChat ? !isOwnMessage : message.SenderId == _currentPartnerId;
            var bubble = CreateCard(incoming ? "#263B50" : "#2B6D67", incoming ? "#466781" : "#4D9C92");
            bubble.HorizontalAlignment = incoming ? HAlignment.Left : HAlignment.Right;
            bubble.HorizontalExpand = false;
            var time = message.Timestamp.ToString(@"hh\:mm");
            var showSender = (isGroupChat || incoming) && !isOwnMessage;
            var contents = new BoxContainer
            {
                Orientation = LayoutOrientation.Vertical,
                HorizontalExpand = true,
                Margin = new Thickness(7, 5),
            };

            if (showSender)
                contents.AddChild(new Label { Text = message.SenderName });

            if (message.ImageData != null)
            {
                try
                {
                    using var stream = new MemoryStream(message.ImageData);
                    contents.AddChild(new TextureRect
                    {
                        Texture = Texture.LoadFromPNGStream(stream),
                        Stretch = TextureRect.StretchMode.KeepAspectCentered,
                        MinSize = new Vector2(180, 140),
                    });
                }
                catch
                {
                    // Radiant Sector: corrupt network image data must not break the chat window.
                }
            }

            if (!string.IsNullOrEmpty(message.Content))
            {
                // Radiant Sector: RichTextLabel wraps plain text to the available chat width instead of clipping it.
                var text = new RichTextLabel { HorizontalExpand = true };
                text.SetMessage(message.Content);
                contents.AddChild(text);
            }
            contents.AddChild(new Label { Text = time });
            bubble.AddChild(contents);
            MessagesContainer.AddChild(bubble);
        }

        if (scrollToBottom)
            _scrollChatFramesRemaining = 3;
        else
            MessagesScroll.SetScrollValue(scrollPosition);
    }

    private void SendMessage()
    {
        var text = MessageInput.Text.Trim();
        if (string.IsNullOrEmpty(text) || _currentPartnerId == 0)
            return;

        OnAction?.Invoke(MessengerUiAction.SendMessage, _currentPartnerId, text, null);
        MessageInput.Clear();
    }

    private Control CreateChatPhotoPicker()
    {
        var card = CreateCard("#27394A", "#5B8CB4");
        var box = new BoxContainer { Orientation = LayoutOrientation.Vertical, HorizontalExpand = true, Margin = new Thickness(6) };
        box.AddChild(new Label { Text = Loc.GetString("messenger-send-photo") });

        for (var i = 0; i < _cameraPhotos.Count; i++)
        {
            var photoIndex = i;
            var select = CreatePhotoPickerButton(i);
            select.OnPressed += _ =>
            {
                OnPhotoAction?.Invoke(MessengerUiAction.SendPhoto, _currentPartnerId, photoIndex);
                _choosingChatPhoto = false;
                BuildChat(scrollToBottom: true);
            };
            box.AddChild(select);
        }

        var capture = new Button { Text = Loc.GetString("messenger-send-photo-capture"), MinHeight = 40 };
        capture.OnPressed += _ => OnPhotoAction?.Invoke(MessengerUiAction.CaptureChatPhoto, _currentPartnerId, -1);
        box.AddChild(capture);
        // Radiant Sector: the picker contents must be attached to its card before it enters the scroll view.
        card.AddChild(box);
        return card;
    }

    private Button CreatePhotoPickerButton(int photoIndex)
    {
        var select = new Button { HorizontalExpand = true, MinHeight = 48 };
        var row = new BoxContainer { Orientation = LayoutOrientation.Horizontal, HorizontalExpand = true, Margin = new Thickness(4) };
        try
        {
            using var stream = new MemoryStream(_cameraPhotos[photoIndex]);
            row.AddChild(new TextureRect
            {
                Texture = Texture.LoadFromPNGStream(stream),
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                MinSize = new Vector2(52, 40),
            });
        }
        catch
        {
            // Radiant Sector: retain a selectable entry when a saved photo cannot be rendered as a thumbnail.
        }

        row.AddChild(new Label
        {
            Text = Loc.GetString("messenger-profile-photo-entry", ("number", photoIndex + 1)),
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center,
        });
        select.AddChild(row);
        return select;
    }

    private static void ResetScroll(ScrollContainer scroll) =>
        scroll.SetScrollValue(Vector2.Zero);

    private static PanelContainer CreateCard(string color, string borderColor) => new()
    {
        PanelOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex(color), BorderColor = Color.FromHex(borderColor), BorderThickness = new Thickness(1) },
        Margin = new Thickness(8, 0, 8, 4),
        HorizontalExpand = true,
    };

    private static Texture LoadAvatarTexture(byte[] profilePhoto)
    {
        using var stream = new MemoryStream(profilePhoto);
        var texture = Texture.LoadFromPNGStream(stream);

        // Radiant Sector: photo frames are wide scene captures; a centered crop keeps avatar thumbnails legible.
        var cropSize = (int) (Math.Min(texture.Width, texture.Height) * 0.6f);
        if (cropSize < 2)
            return texture;

        var left = (texture.Width - cropSize) / 2;
        var top = (texture.Height - cropSize) / 2;
        return new AtlasTexture(texture, UIBox2.FromDimensions(new Vector2(left, top), new Vector2(cropSize, cropSize)));
    }

    private static Control CreateAvatar(string name, string color, byte[]? profilePhoto = null)
    {
        if (profilePhoto != null)
        {
            try
            {
                // Radiant Sector: a photo thumbnail owns its full fixed area, avoiding a second frame that can shift in list rows.
                return new TextureRect
                {
                    Texture = LoadAvatarTexture(profilePhoto),
                    Stretch = TextureRect.StretchMode.Scale,
                    CanShrink = true,
                    MinSize = new Vector2(32, 32),
                    MaxSize = new Vector2(32, 32),
                    HorizontalAlignment = HAlignment.Center,
                    VerticalAlignment = VAlignment.Center,
                    RectClipContent = true,
                };
            }
            catch
            {
                // Radiant Sector: fall back to the initial when a stored profile image is invalid.
            }
        }

        var avatar = new PanelContainer
        {
            PanelOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex(color), BorderColor = Color.FromHex("#8BB6D8"), BorderThickness = new Thickness(1) },
            MinSize = new Vector2(32, 32),
            MaxSize = new Vector2(32, 32),
            VerticalAlignment = VAlignment.Center,
        };
        avatar.AddChild(new Label { Text = string.IsNullOrWhiteSpace(name) ? "?" : name[..1].ToUpperInvariant(), Align = Label.AlignMode.Center, VerticalAlignment = VAlignment.Center });
        return avatar;
    }

    private static PanelContainer CreateUnreadBadge(int count)
    {
        var badge = new PanelContainer { PanelOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#4FA3E3"), BorderColor = Color.FromHex("#8BC8F5"), BorderThickness = new Thickness(1) }, MinSize = new Vector2(24, 20), VerticalAlignment = VAlignment.Center };
        badge.AddChild(new Label { Text = count.ToString(), Align = Label.AlignMode.Center, VerticalAlignment = VAlignment.Center });
        return badge;
    }
}
