using System.IO;
using System.Numerics;
using Content.Shared.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.Input;
using Robust.Shared.Maths;
using Robust.Shared.Timing;
using SixLabors.ImageSharp;

namespace Content.Client.CartridgeLoader.Cartridges;

/// <summary>
/// Radiant Sector: compact live camera preview embedded in the PDA program area.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class PdaCameraUiFragment : BoxContainer
{
    [Dependency] private readonly IEntityManager _entityManager = default!;

    private EntityUid? _loader;
    private bool _selfieMode;
    private Vector2 _cameraOffset;
    private Vector2 _moveInput;
    private float _cameraZoom = 1f;
    private List<byte[]> _photos = [];
    private int _selectedPhotoIndex = -1;

    public event Action? OnCapture;
    public event Action? OnToggleSelfie;
    public event Action? OnToggleGallery;
    // Radiant Sector: the UI requests deletion; the server remains the photo-store authority.
    public event Action<int>? OnDeletePhoto;

    public PdaCameraUiFragment()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        // Radiant Sector: ScalingViewport needs a real render resolution, like the normal camera window.
        // Radiant Sector: retain the regular camera's square framing so it fits inside the PDA window.
        CameraView.ViewportSize = new Vector2i(210, 210);
        PhotoButton.Disabled = true;
        PhotoButton.OnPressed += _ => OnCapture?.Invoke();
        SelfieButton.OnPressed += _ => OnToggleSelfie?.Invoke();
        GalleryButton.OnPressed += _ => OnToggleGallery?.Invoke();
        GalleryGridButton.OnPressed += _ => ShowGalleryGrid();
        GalleryPreviousButton.OnPressed += _ => SelectAdjacentPhoto(-1);
        GalleryNextButton.OnPressed += _ => SelectAdjacentPhoto(1);
        GalleryDeleteButton.OnPressed += _ => DeleteSelectedPhoto();
        PanLeftButton.OnPressed += _ => AdjustCamera(new Vector2(-0.5f, 0f));
        PanUpButton.OnPressed += _ => AdjustCamera(new Vector2(0f, 0.5f));
        PanDownButton.OnPressed += _ => AdjustCamera(new Vector2(0f, -0.5f));
        PanRightButton.OnPressed += _ => AdjustCamera(new Vector2(0.5f, 0f));
        // Radiant Sector: lower eye zoom means a closer frame, matching the regular camera.
        ZoomOutButton.OnPressed += _ => AdjustZoom(0.1f);
        ZoomInButton.OnPressed += _ => AdjustZoom(-0.1f);
    }

    public void UpdateState(PdaCameraUiState state)
    {
        _loader = _entityManager.GetEntity(state.Loader);
        _selfieMode = state.SelfieMode;
        _photos = state.Photos;
        if (_selectedPhotoIndex >= _photos.Count)
            _selectedPhotoIndex = -1;
        if (!state.GalleryOpen)
            _selectedPhotoIndex = -1;
        SelfieButton.Text = Loc.GetString(_selfieMode ? "pda-camera-mode-selfie" : "pda-camera-mode-normal");
        PhotoCountLabel.Text = Loc.GetString("pda-camera-photo-count", ("count", state.Photos.Count));
        CameraFrame.Visible = !state.GalleryOpen;
        GalleryPanel.Visible = state.GalleryOpen;
        CameraActionRow.Visible = !state.GalleryOpen;
        NavigationRow.Visible = !state.GalleryOpen;
        GalleryActionRow.Visible = state.GalleryOpen;
        GalleryButton.Text = Loc.GetString(state.GalleryOpen ? "pda-camera-camera" : "pda-camera-gallery");
        BuildGallery();

        if (_entityManager.TryGetComponent<EyeComponent>(_loader, out var eye))
            CameraView.Eye = eye.Eye;

        PhotoButton.Disabled = state.GalleryOpen || CameraView.Eye == null;
        SelfieButton.Disabled = state.GalleryOpen;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_loader == null || !_entityManager.TryGetComponent<EyeComponent>(_loader, out var eye))
            return;

        // Keep this separate eye aligned with the PDA owner without touching the player's main viewport.
        // Radiant Sector: entity systems are retrieved from the entity manager, not the UI IoC container.
        _cameraOffset += _moveInput * 3f * args.DeltaSeconds;
        _cameraOffset = Vector2.Clamp(_cameraOffset, new Vector2(-4f), new Vector2(4f));

        var eyeSystem = _entityManager.System<EyeSystem>();
        var selfieOffset = _selfieMode ? new Vector2(0f, 1.2f) : Vector2.Zero;
        eyeSystem.SetOffset(_loader.Value, _cameraOffset + selfieOffset, eye);
        eyeSystem.SetRotation(_loader.Value, _selfieMode ? Angle.FromDegrees(180) : Angle.Zero, eye);
        eyeSystem.SetZoom(_loader.Value, new Vector2(_cameraZoom), eye);
    }

    protected override void MouseWheel(GUIMouseWheelEventArgs args)
    {
        base.MouseWheel(args);
        AdjustZoom(-args.Delta.Y * 0.25f);
    }

    protected override void KeyBindDown(GUIBoundKeyEventArgs args)
    {
        base.KeyBindDown(args);
        UpdateMoveInput(args.Function, 1f);
    }

    protected override void KeyBindUp(GUIBoundKeyEventArgs args)
    {
        base.KeyBindUp(args);
        UpdateMoveInput(args.Function, -1f);
    }

    private void UpdateMoveInput(BoundKeyFunction function, float delta)
    {
        if (function == EngineKeyFunctions.MoveUp)
            _moveInput.Y += delta;
        if (function == EngineKeyFunctions.MoveDown)
            _moveInput.Y -= delta;
        if (function == EngineKeyFunctions.MoveRight)
            _moveInput.X += delta;
        if (function == EngineKeyFunctions.MoveLeft)
            _moveInput.X -= delta;
    }

    private void AdjustCamera(Vector2 offset)
    {
        _cameraOffset = Vector2.Clamp(_cameraOffset + offset, new Vector2(-4f), new Vector2(4f));
    }

    private void AdjustZoom(float amount)
    {
        _cameraZoom = Math.Clamp(_cameraZoom + amount, 0.2f, 1f);
    }

    private void BuildGallery()
    {
        GalleryContainer.RemoveAllChildren();
        GalleryScroll.Visible = _selectedPhotoIndex < 0;
        PhotoViewer.Visible = _selectedPhotoIndex >= 0;
        GalleryPreviousButton.Disabled = _selectedPhotoIndex < 0 || _photos.Count < 2;
        GalleryNextButton.Disabled = _selectedPhotoIndex < 0 || _photos.Count < 2;
        GalleryDeleteButton.Disabled = _selectedPhotoIndex < 0;

        if (_selectedPhotoIndex >= 0)
        {
            try
            {
                using var stream = new MemoryStream(_photos[_selectedPhotoIndex]);
                SelectedPhoto.Texture = Texture.LoadFromPNGStream(stream);
            }
            catch
            {
                // Radiant Sector: invalid photo data returns the user to the usable gallery grid.
                _selectedPhotoIndex = -1;
                BuildGallery();
            }

            return;
        }

        SelectedPhoto.Texture = null;
        for (var i = 0; i < _photos.Count; i++)
        {
            try
            {
                using var stream = new MemoryStream(_photos[i]);
                var index = i;
                var select = new Button
                {
                    MinSize = new Vector2(92, 92),
                    MaxSize = new Vector2(92, 92),
                    ToolTip = Loc.GetString("pda-camera-gallery-open"),
                };
                select.AddChild(new TextureRect
                {
                    Texture = Texture.LoadFromPNGStream(stream),
                    Stretch = TextureRect.StretchMode.KeepAspectCentered,
                    MinSize = new Vector2(86, 86),
                    MaxSize = new Vector2(86, 86),
                });
                select.OnPressed += _ =>
                {
                    _selectedPhotoIndex = index;
                    BuildGallery();
                };
                GalleryContainer.AddChild(select);
            }
            catch
            {
                // Radiant Sector: a corrupted saved photo must not prevent opening the gallery.
            }
        }
    }

    private void ShowGalleryGrid()
    {
        _selectedPhotoIndex = -1;
        BuildGallery();
    }

    private void SelectAdjacentPhoto(int direction)
    {
        if (_selectedPhotoIndex < 0 || _photos.Count < 2)
            return;

        _selectedPhotoIndex = (_selectedPhotoIndex + direction + _photos.Count) % _photos.Count;
        BuildGallery();
    }

    private void DeleteSelectedPhoto()
    {
        if (_selectedPhotoIndex < 0)
            return;

        var deletedIndex = _selectedPhotoIndex;
        _selectedPhotoIndex = -1;
        OnDeletePhoto?.Invoke(deletedIndex);
    }

    public void RenderImage(Action<byte[]> callback)
    {
        if (CameraView.Eye == null)
            return;

        CameraView.Screenshot(image =>
        {
            using var data = new MemoryStream();
            image.SaveAsPng(data);
            image.Dispose();
            callback(data.ToArray());
        });
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing && _loader != null && _entityManager.TryGetComponent<EyeComponent>(_loader, out var eye))
        {
            var eyeSystem = _entityManager.System<EyeSystem>();
            eyeSystem.SetOffset(_loader.Value, Vector2.Zero, eye);
            eyeSystem.SetRotation(_loader.Value, Angle.Zero, eye);
            eyeSystem.SetZoom(_loader.Value, Vector2.One, eye);
        }

        base.Dispose(disposing);
    }
}
