using Content.Client.UserInterface.Controls;
using Content.Shared._radiant.WeaponSerial;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._radiant.WeaponSerial;

/// <summary>
///     Weapon registration console window: a short summary of the weapon in the
///     slot (serial / name / class / origin / owner), a one-time "stamp the
///     number" button for weapons without a number, and the "change owner" edit.
///     Like a clerk's counter: you see the weapon's card and type the owner
///     name right into it.
///     The PDA stays read-only: it only displays the data from the server
///     snapshot.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class WeaponRegistrationConsoleWindow : FancyWindow
{
    /// <summary>
    ///     The "Change owner" button was pressed: the BUI sends
    ///     WeaponRegistrationSetOwner to the server. The serial is not sent —
    ///     the server reads the slot itself.
    /// </summary>
    public event Action<string?>? OnOwnerSave;

    /// <summary>
    ///     The one-time "stamp the number" button was pressed: the BUI sends
    ///     WeaponRegistrationStampSerial. Only shown while the number is null.
    /// </summary>
    public event Action? OnStamp;

    public WeaponRegistrationConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        // Cap the owner name at the source: IsValid makes LineEdit throw away any
        // edit that would exceed the limit, so an over-long name cannot even
        // appear in the field — neither typed nor pasted. The same constant is
        // checked again on the server (WeaponSerialSystem.OnConsoleSetOwner),
        // because a client can always lie.
        OwnerEdit.IsValid = text => text.Length <= SharedWeaponSerialSystem.MaxOwnerLength;

        SaveOwnerButton.OnPressed += _ => OnOwnerSave?.Invoke(NormalizeOwner(OwnerEdit.Text));
        OwnerEdit.OnTextEntered += args => OnOwnerSave?.Invoke(NormalizeOwner(args.Text));
        StampButton.OnPressed += _ => OnStamp?.Invoke();
    }

    /// <summary>
    ///     Show the summary.
    ///     WeaponName == null — the slot is empty, show the "insert a weapon" hint.
    ///     Serial == null — the weapon has no number yet: show the one-time
    ///     "stamp the number" button instead of the serial line and owner edit.
    ///     The edit field is pre-filled with the current owner; an empty field +
    ///     Save clears the owner.
    /// </summary>
    public void UpdateState(WeaponRegistrationConsoleState state)
    {
        var hasWeapon = state.WeaponName != null;
        var hasSerial = state.Serial != null;
        EmptyHint.Visible = !hasWeapon;
        SummaryBox.Visible = hasWeapon;
        StampButton.Visible = hasWeapon && !hasSerial;
        OwnerEdit.Visible = hasSerial;
        SaveOwnerButton.Visible = hasSerial;
        if (!hasWeapon)
            return;

        DetailWeapon.SetMessage(BuildMessage("weapon-registry-detail-weapon", ("name", state.WeaponName ?? string.Empty)));
        DetailSerial.SetMessage(hasSerial
            ? BuildMessage("weapon-registry-detail-serial", ("serial", state.Serial ?? string.Empty))
            : BuildMessage("weapon-serial-wiped"));
        DetailClass.SetMessage(state.WeaponClass == null
            ? BuildMessage("weapon-registry-detail-class-unset")
            : BuildMessage("weapon-registry-detail-class", ("class", Loc.GetString(state.WeaponClass))));
        DetailOrigin.SetMessage(state.Origin == null
            ? BuildMessage("weapon-registry-detail-origin-unset")
            : BuildMessage("weapon-registry-detail-origin", ("origin", Loc.GetString(state.Origin))));
        DetailOwner.SetMessage(state.Owner == null
            ? BuildMessage("weapon-registry-detail-owner-unset")
            : BuildMessage("weapon-registry-detail-owner-set", ("owner", state.Owner)));

        // Pre-fill: if the player just saved the name, the server push returns
        // the same value — the field does not flicker. The server is the source
        // of truth, and the push only arrives when the slot content changes or
        // on save.
        OwnerEdit.Text = state.Owner ?? string.Empty;
    }

    private static string? NormalizeOwner(string text)
    {
        var trimmed = text.Trim();
        return string.IsNullOrEmpty(trimmed) ? null : trimmed;
    }

    private static FormattedMessage BuildMessage(string fluentId, params (string, object)[] args)
    {
        var msg = new FormattedMessage();
        msg.AddMarkupPermissive(Loc.GetString(fluentId, args));
        return msg;
    }
}
