using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._radiant.WeaponSerial;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Log;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._radiant.WeaponSerial;

[GenerateTypedNameReferences]
public sealed partial class WeaponRegistryUiFragment : BoxContainer
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IComponentFactory _componentFactory = default!;

    private string? _selectedSerial;
    private List<WeaponRegistryEntry> _registryEntries = new();

    // Raised when the player hits the refresh button, so the wrapper can ask
    // the server to re-send the current registry snapshot.
    // NOTE: the PDA is read-only — the owner is entered only in the weapon
    // registration console. OnOwnerSaved and SaveOwner were removed deliberately.
    public event Action? OnRegistryRefresh;

    public WeaponRegistryUiFragment()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        RegistrySearchBar.OnTextChanged += OnRegistrySearchTextChanged;
        RegistryRefreshButton.OnPressed += _ => OnRegistryRefresh?.Invoke();
    }

    /// <summary>
    ///     Renders the registry entries pushed by WeaponSerialSystem.
    /// </summary>
    public void UpdateRegistry(List<WeaponRegistryEntry> entries, bool refresh = true)
    {
        if (refresh)
        {
            _registryEntries = entries.DistinctBy(e => e.Serial).ToList();

            // A fresh server snapshot while an entry is selected (e.g. right after an
            // owner name was saved) must refresh the detail pane too, otherwise the
            // owner label would keep showing the previous value until re-selection.
            if (_selectedSerial is { } serial
                && _registryEntries.FirstOrDefault(e => e.Serial == serial) is { } updated)
            {
                RenderRegistryDetail(updated);
            }
        }

        // Re-render goes through the search filter: if the player is mid-search,
        // a pushed server update must not reset their filter.
        RenderRegistry(FilterRegistry(RegistrySearchBar.Text));
    }

    /// <summary>
    ///     Client-side filtering. The whole registry is already in memory, so there
    ///     is no reason to round-trip the server just to narrow the list.
    /// </summary>
    private List<WeaponRegistryEntry> FilterRegistry(string? text)
    {
        if (String.IsNullOrWhiteSpace(text))
            return _registryEntries;

        return _registryEntries.FindAll(e =>
            e.Serial.Contains(text, StringComparison.OrdinalIgnoreCase) ||
            e.Name.Contains(text, StringComparison.OrdinalIgnoreCase) ||
            (e.Owner != null && e.Owner.Contains(text, StringComparison.OrdinalIgnoreCase)) ||
            e.Rarity.ToString().Contains(text, StringComparison.OrdinalIgnoreCase));
    }

    private void OnRegistrySearchTextChanged(LineEdit.LineEditEventArgs args)
    {
        // args.Text, not RegistrySearchBar.Text: the event args carry the exact
        // value at the moment of the event, which is the honest source here.
        RenderRegistry(FilterRegistry(args.Text));
    }

    /// <summary>
    ///     Draws the given subset of entries and picks the right "empty" message:
    ///     the registry has no weapons at all vs. the filter matched nothing.
    /// </summary>
    private void RenderRegistry(List<WeaponRegistryEntry> toShow)
    {
        RegistryList.GenerateItem = GenerateRegistryItem;
        RegistryList.ItemPressed = OnRegistryItemSelected;
        var dataList = new List<ListData>();
        foreach (var entry in toShow)
            dataList.Add(new WeaponRegistryListData(entry));
        RegistryList.PopulateList(dataList);

        var empty = toShow.Count == 0;
        var filterActive = !String.IsNullOrWhiteSpace(RegistrySearchBar.Text);
        NoRegistryEntries.Visible = empty && !filterActive;
        NoRegistryMatches.Visible = empty && filterActive;
        RegistryList.Visible = !empty;
        if (empty)
        {
            RegistryDetail.Visible = false;
            _selectedSerial = null;
        }
    }

    private void OnRegistryItemSelected(BaseButton.ButtonEventArgs args, ListData data)
    {
        if (data is not WeaponRegistryListData(var entry))
            return;

        _selectedSerial = entry.Serial;
        RenderRegistryDetail(entry);
    }

    private void RenderRegistryDetail(WeaponRegistryEntry entry)
    {
        DetailWeapon.SetMessage(BuildMessage("weapon-registry-detail-weapon", ("name", entry.Name)));
        DetailSerial.SetMessage(BuildMessage("weapon-registry-detail-serial", ("serial", entry.Serial)));
        // The loc keys are lowercase-first while enum members start with an upper-case
        // letter (e.g. UniqueWrittenoff -> uniqueWrittenoff), so fold the first character.
        var rarity = entry.Rarity.ToString();
        var rarityName = string.Concat(rarity.Substring(0, 1).ToLowerInvariant(), rarity.Substring(1));
        var rarityKey = string.Concat("weapon-registry-rarity-", rarityName);
        DetailRarity.SetMessage(BuildMessage(rarityKey));
        DetailOwner.SetMessage(entry.Owner == null
            ? BuildMessage("weapon-registry-detail-owner-unset")
            : BuildMessage("weapon-registry-detail-owner-set", ("owner", entry.Owner)));

        // Read-only: the owner edit field lives only in the weapon registration console.
        RegistryDetail.Visible = true;
    }

    private void GenerateRegistryItem(ListData data, ListContainerButton button)
    {
        if (data is not WeaponRegistryListData(var entry))
            return;

        // Weapon icon on the left, taken from the entity prototype (same pattern
        // the market menu uses). The icon lives INSIDE the row button, so clicking
        // it selects the entry — the whole row is one clickable button. The scale
        // is small enough that the serial number still fits in the 192px row.
        var icon = new TextureRect
        {
            TextureScale = new(1.8f),
            VerticalAlignment = VAlignment.Center,
            HorizontalAlignment = HAlignment.Center,
            Margin = new(2f, 2f, 6f, 2f),
        };
        if (_prototypeManager.TryIndex<EntityPrototype>(entry.PrototypeId, out var prototype)
            && prototype.TryGetComponent(out SpriteComponent? sprite, _componentFactory))
        {
            icon.Texture = sprite.Icon?.Default;
        }

        // Show the serial number and the weapon name as TWO stacked lines so both
        // stay readable inside the 192px row: line 1 = serial, line 2 = weapon name.
        // The owner (when set) is a small third line, kept out of the way.
        var texts = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center,
            Margin = new(2f, 2f, 8f, 2f),
        };

        // 1st line: serial number.
        texts.AddChild(new Label() { Text = entry.Serial, StyleClasses = { "LabelSmall" } });

        // 2nd line: weapon name.
        var nameLabel = new Label() { Text = entry.Name, ClipText = true, HorizontalExpand = true };
        nameLabel.AddStyleClass("LabelSmall");
        texts.AddChild(nameLabel);

        // Optional 3rd line: owner, small gray.
        if (entry.Owner is { } owner)
        {
            var ownerLabel = new Label()
            {
                Text = owner,
                ClipText = true,
                ToolTip = owner,
                StyleClasses = { "LabelSmall" },
                FontColorOverride = Color.DarkGray,
            };
            texts.AddChild(ownerLabel);
        }

        var row = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center,
        };
        row.AddChild(icon);
        row.AddChild(texts);
        button.AddChild(row);
        button.AddStyleClass(ListContainer.StyleClassListContainerButton);

        if (entry.Serial.Equals(_selectedSerial))
        {
            button.Pressed = true;
            // Same workaround as the wanted list: Pressed change does not raise the event.
            OnRegistryItemSelected(
                new(button, new(new(), BoundKeyState.Down, new(), false, new(), new())),
                data);
        }
    }

    private FormattedMessage BuildMessage(string fluentId, params (string, object)[] args)
    {
        var msg = new FormattedMessage();
        msg.AddMarkupPermissive(Loc.GetString(fluentId, args));
        return msg;
    }
}

internal record WeaponRegistryListData(WeaponRegistryEntry Entry) : ListData;

