using Content.Client.UserInterface.Controls;
using Content.Shared._radiant.WeaponSerial;
using Content.Shared.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._radiant.WeaponSerial;

/// <summary>
///     Weapon registration console window: a short summary of the weapon in the
///     slot (serial / name / rarity / owner) + owner editing.
///     Like a clerk's counter: you see the weapon's card and type the owner
///     name right into it, then press "Save".
///     The PDA stays read-only: it only displays the owner from the server
///     snapshot.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class WeaponRegistrationConsoleWindow : FancyWindow
{
    /// <summary>
    ///     The "Save" button was pressed: the BUI sends WeaponRegistrationSetOwner
    ///     to the server. The serial is not sent — the server reads the slot itself.
    /// </summary>
    public event Action<string?>? OnOwnerSave;

    public WeaponRegistrationConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        SaveOwnerButton.OnPressed += _ => OnOwnerSave?.Invoke(NormalizeOwner(OwnerEdit.Text));
        OwnerEdit.OnTextEntered += args => OnOwnerSave?.Invoke(NormalizeOwner(args.Text));
    }

    /// <summary>
    ///     Show the summary. Serial == null means the slot is empty — show the hint.
    ///     The edit field is pre-filled with the current owner; an empty field +
    ///     Save clears the owner.
    /// </summary>
    public void UpdateState(WeaponRegistrationConsoleState state)
    {
        var hasWeapon = state.Serial != null;
        EmptyHint.Visible = !hasWeapon;
        SummaryBox.Visible = hasWeapon;
        if (!hasWeapon)
            return;

        DetailWeapon.SetMessage(BuildMessage("weapon-registry-detail-weapon", ("name", state.WeaponName ?? string.Empty)));
        DetailSerial.SetMessage(BuildMessage("weapon-registry-detail-serial", ("serial", state.Serial ?? string.Empty)));

        // The rarity localization key arrives from the server already in the
        // right case (common / uniqueWrittenoff), so no ToString is needed here.
        DetailRarity.SetMessage(BuildMessage($"weapon-registry-rarity-{state.WeaponRarity ?? "common"}"));

        DetailOwner.SetMessage(state.Owner == null
            ? BuildMessage("weapon-registry-detail-owner-unset")
            : BuildMessage("weapon-registry-detail-owner-set", ("owner", state.Owner)));

        // Pre-fill: if the player just saved the name, the server push returns
        // the same value — the field does not flicker. The server is the source
        // of truth, and the push only arrives when the slot content changes or
        // on save.
        OwnerEdit.Text = state.Owner ?? string.Empty;
    }

    private static string? NormalizeOwner(string text)
    {
        var trimmed = text.Trim();
        return string.IsNullOrEmpty(trimmed) ? null : trimmed;
    }

    private static FormattedMessage BuildMessage(string fluentId, params (string, object)[] args)
    {
        var msg = new FormattedMessage();
        msg.AddMarkupPermissive(Loc.GetString(fluentId, args));
        return msg;
    }
}
