- type: job
  id: SeparatistsWarden
  name: job-name-separatists-warden
  description: job-description-separatists-warden
  playTimeTracker: JobSeparatistsWarden
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 28800 # 8 hours Radiant_Sector
  startingGear: SeparatistsWardenGear
  icon: "JobIconSeparatistsWarden" 
  supervisors: job-supervisors-hire
  weight: 34
  displayWeight: 34
  access:
  - Separatists
  accessGroups: # Frontier
  - GeneralAccess
  special:
  - !type:AddComponentSpecial
    components:
    - type: SpecialSectorStationRecord # must be given on spawn
      recordGeneration: FalseRecord
  - !type:AddImplantSpecial
    implants: [ SeparatistsTrackingImplant ]
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: SeparatistsWardenGear
  storage:
    back:
    - ClothingMaskGasSeparatist
    - BaseSeparatistUplinkCrew
    - SeparatistToken1