- type: job
  id: SeparatistsOperative
  name: job-name-separatists-operative
  description: job-description-separatists-operative
  playTimeTracker: JobSeparatistsOperative
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 86400 # 24 hours Radiant_Sector
    - !type:DepartmentTimeRequirement
      department: Separatists
      time: 43200 # 12 hours Radiant_Sector
    - !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 21600 # 6 hours Radiant_Sector
  startingGear: SeparatistsOperativeGear
  alwaysUseSpawner: true
  icon: "JobIconSeparatistsOperative" 
  supervisors: job-supervisors-hire
  weight: 36
  displayWeight: 36
  newPlayerMessage: false
  access:
  - Separatists
  accessGroups: # Frontier
  - GeneralAccess
  special:
  - !type:AddComponentSpecial
    components:
    - type: MailDisabled
    - type: SpecialSectorStationRecord # must be given on spawn
      recordGeneration: FalseRecord
  - !type:AddImplantSpecial
    implants: [ SeparatistsTrackingImplant ]
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: SeparatistsOperativeGear
  equipment:
    pocket1: WeaponPistolWhisper
  storage:
    back:
    - ClothingMaskGasSeparatist
    - MagazinePistol25ACP
    - BaseSeparatistUplinkCrew
    - SeparatistToken1
