using Content.Shared._radiant.Humanoid;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._radiant.Humanoid;

[GenerateTypedNameReferences]
public sealed partial class GradientHairColorPanel : BoxContainer
{
    [Dependency] private readonly MarkingManager _markingManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    public HumanoidVisualLayers TargetLayer { get; set; } = HumanoidVisualLayers.Hair;

    public Action? OnChanged;

    private bool _updating;

    public GradientHairColorPanel()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ModeButton.AddItem(Loc.GetString("hair-gradient-mode-solid"), (int) HairColoringMode.Solid);
        ModeButton.AddItem(Loc.GetString("hair-gradient-mode-gradient"), (int) HairColoringMode.Gradient);

        foreach (HairGradientDirection direction in Enum.GetValues<HairGradientDirection>())
        {
            DirectionButton.AddItem(Loc.GetString($"hair-gradient-direction-{direction.ToString().ToLower()}"), (int) direction);
        }

        ModeButton.OnItemSelected += args =>
        {
            ModeButton.SelectId(args.Id);
            GradientOptions.Visible = args.Id == (int) HairColoringMode.Gradient;
            if (!_updating)
                OnChanged?.Invoke();
        };

        DirectionButton.OnItemSelected += args =>
        {
            DirectionButton.SelectId(args.Id);
            if (!_updating)
                OnChanged?.Invoke();
        };

        SecondaryColorSelector.SelectorType = ColorSelectorSliders.ColorSelectorType.Hsv;
        SecondaryColorSelector.OnColorChanged += _ =>
        {
            if (!_updating)
                OnChanged?.Invoke();
        };
    }

    public void UpdateFromAppearance(HumanoidCharacterAppearance appearance, string species)
    {
        _updating = true;

        TitleLabel.Text = TargetLayer == HumanoidVisualLayers.Hair
            ? Loc.GetString("hair-gradient-hair-title")
            : Loc.GetString("hair-gradient-facial-hair-title");

        var canCustomize = HairColoringHelper.CanUseCustomHairColor(species, TargetLayer, _markingManager, _prototypeManager);
        Visible = canCustomize;
        ModeButton.Disabled = !canCustomize;
        DirectionButton.Disabled = !canCustomize;

        if (!canCustomize)
        {
            _updating = false;
            return;
        }

        var mode = TargetLayer == HumanoidVisualLayers.Hair
            ? appearance.HairColoringMode
            : appearance.FacialHairColoringMode;
        var secondary = TargetLayer == HumanoidVisualLayers.Hair
            ? appearance.HairGradientColor
            : appearance.FacialHairGradientColor;
        var direction = TargetLayer == HumanoidVisualLayers.Hair
            ? appearance.HairGradientDirection
            : appearance.FacialHairGradientDirection;

        ModeButton.SelectId((int) mode);
        GradientOptions.Visible = mode == HairColoringMode.Gradient;
        SecondaryColorSelector.Color = secondary;
        DirectionButton.SelectId((int) direction);

        _updating = false;
    }

    public HairColoringMode GetMode() => (HairColoringMode) ModeButton.SelectedId;

    public Color GetSecondaryColor() => SecondaryColorSelector.Color;

    public HairGradientDirection GetDirection() => (HairGradientDirection) DirectionButton.SelectedId;
}
