using Content.Client.Lobby;
using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._radiant.Lobby;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;

namespace Content.Client._radiant.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class SpeciesSelectionWindow : FancyWindow
{
    private readonly IPrototypeManager _prototypes;
    private readonly IEntityManager _entities;
    private readonly LobbyUIController _lobby;
    private readonly HumanoidCharacterProfile _profile;
    private EntityUid? _previewEntity;

    public event Action<ProtoId<SpeciesPrototype>>? OnSpeciesChosen;

    public SpeciesSelectionWindow(
        HumanoidCharacterProfile profile,
        IPrototypeManager prototypes,
        IEntityManager entities,
        LobbyUIController lobby)
    {
        RobustXamlLoader.Load(this);
        _profile = profile;
        _prototypes = prototypes;
        _entities = entities;
        _lobby = lobby;

        Title = Loc.GetString("species-selection-window-title");
        Choose.OnPressed += _ => OnSpeciesChosen?.Invoke(_selectedSpecies);

        PopulateSpecies();
        SelectSpecies(profile.Species);
    }

    private ProtoId<SpeciesPrototype> _selectedSpecies = "Human";

    private void PopulateSpecies()
    {
        var species = _prototypes.EnumeratePrototypes<SpeciesPrototype>()
            .Where(x => x.RoundStart)
            .OrderBy(x => Loc.GetString(x.Name))
            .ToList();

        var loreBySpecies = _prototypes.EnumeratePrototypes<SpeciesLorePrototype>()
            .ToDictionary(x => x.Species.Id, x => x);

        foreach (var group in species.GroupBy(x => loreBySpecies.GetValueOrDefault(x.ID)?.Category ?? "species-lore-category-other"))
        {
            SpeciesList.AddChild(new Label
            {
                Text = Loc.GetString(group.Key),
                FontColorOverride = Color.FromHex("#F2F6FB"),
                Margin = new Thickness(2, 8, 2, 2),
            });

            foreach (var speciesPrototype in group)
            {
                var button = new SpeciesEntryButton(speciesPrototype.ID)
                {
                    Text = Loc.GetString(speciesPrototype.Name),
                    HorizontalExpand = true,
                    ToggleMode = true,
                    Margin = new Thickness(0, 1),
                };
                button.OnPressed += _ => SelectSpecies(speciesPrototype.ID);
                SpeciesList.AddChild(button);
            }
        }
    }

    private void SelectSpecies(ProtoId<SpeciesPrototype> speciesId)
    {
        _selectedSpecies = speciesId;
        var species = _prototypes.Index(speciesId);

        foreach (var child in SpeciesList.Children)
        {
            if (child is SpeciesEntryButton button)
                button.Pressed = button.Species == speciesId;
        }

        SpeciesName.Text = Loc.GetString(species.Name);
        Details.DisposeAllChildren();

        if (_prototypes.TryIndex<SpeciesLorePrototype>(speciesId.Id, out var lore))
        {
            Category.Text = Loc.GetString(lore.Category);
            AddSection("species-selection-lore", lore.Lore);
            AddListSection("species-selection-biology", lore.Biology, "c4a6ff");
            AddGameplayStats(lore.LoreHeight, lore.GameplayStats);
            AddListSection("species-selection-abilities", lore.Abilities, "b68cff");
            AddListSection("species-selection-diet", lore.Diet, "e6c77a");
            AddLanguageSection(lore.Languages);
            AddListSection("species-selection-communication", lore.Communication, "c4a6ff");
            AddListSection("species-selection-culture", lore.Culture, "d5b678");
            AddListSection("species-selection-interactions", lore.InteractionTips, "e6c77a");
            AddListSection("species-selection-features", lore.Features, "69d391");
            AddListSection("species-selection-roleplay", lore.RoleplayTips, "f1c66e");
            AddWikiLink(speciesId);
        }
        else
        {
            Category.Text = Loc.GetString("species-lore-category-other");
            AddSection("species-selection-no-lore", "species-selection-no-lore-text");
        }

        UpdatePreview(speciesId);
    }

    private void AddSection(string title, string text)
    {
        Details.AddChild(new Label
        {
            Text = Loc.GetString(title),
            StyleClasses = { "LabelHeading" },
            Margin = new Thickness(0, 4, 0, 2),
        });
        Details.AddChild(new RichTextLabel
        {
            MaxWidth = 600,
            Margin = new Thickness(2, 0, 2, 8),
            Text = Loc.GetString(text),
        });
    }

    private void AddGameplayStats(string? loreHeight, List<string> stats)
    {
        Details.AddChild(new Label
        {
            Text = Loc.GetString("species-selection-gameplay-stats"),
            StyleClasses = { "LabelHeading" },
            Margin = new Thickness(0, 4, 0, 2),
        });

        if (!string.IsNullOrWhiteSpace(loreHeight))
        {
            Details.AddChild(new RichTextLabel
            {
                MaxWidth = 600,
                Margin = new Thickness(2, 1),
                Text = $"[color=#F2F6FB]•[/color] {Loc.GetString(loreHeight)}",
            });
        }

        foreach (var stat in stats)
        {
            Details.AddChild(new RichTextLabel
            {
                MaxWidth = 600,
                Margin = new Thickness(2, 1),
                Text = $"[color=#F2F6FB]•[/color] {Loc.GetString(stat)}",
            });
        }
    }

    private void AddListSection(string title, List<string> entries, string color)
    {
        if (entries.Count == 0)
            return;

        Details.AddChild(new Label
        {
            Text = Loc.GetString(title),
            StyleClasses = { "LabelHeading" },
            Margin = new Thickness(0, 4, 0, 2),
        });

        foreach (var entry in entries)
        {
            Details.AddChild(new RichTextLabel
            {
                MaxWidth = 600,
                Margin = new Thickness(2, 1),
                Text = $"[color=#{color}]•[/color] {Loc.GetString(entry)}",
            });
        }
    }

    /// <summary>
    /// Keeps languages easy to distinguish at a glance in the species reference.
    /// The colours match the chat colours used by the language system.
    /// </summary>
    private void AddLanguageSection(List<string> languages)
    {
        if (languages.Count == 0)
            return;

        Details.AddChild(new Label
        {
            Text = Loc.GetString("species-selection-languages"),
            StyleClasses = { "LabelHeading" },
            Margin = new Thickness(0, 4, 0, 2),
        });

        foreach (var language in languages)
        {
            var color = language switch
            {
                "species-lore-language-galactic" => "F2F6FB",
                "species-lore-language-draconic" => "2ACA2A",
                "species-lore-language-bubblish" => "24D1B9",
                "species-lore-language-rootspeak" => "A64E14",
                "species-lore-language-vox" => "A489A0",
                "species-lore-language-nian" => "C7DF2E",
                "species-lore-language-chittin" => "B0B0B0",
                "species-lore-language-canilunzt" => "D69B3D",
                "species-lore-language-siikmaas" => "D6A36E",
                "species-lore-language-schechi" => "4DBFD9",
                "species-lore-language-nehina" => "5BB7D5",
                "species-lore-language-nekomimetic" => "E5A1C7",
                "species-lore-language-shadowkin" => "C29EFF",
                "species-lore-language-khazdar" => "C78E42",
                "species-lore-language-kansei" => "D95B67",
                "species-lore-language-aerian" => "8ED5E8",
                "species-lore-language-krikli" => "A7C746",
                "species-lore-language-shelar" => "B5B9DF",
                "species-lore-language-arcanian" => "D888E8",
                _ => "8FC5FF",
            };

            Details.AddChild(new RichTextLabel
            {
                MaxWidth = 600,
                Margin = new Thickness(2, 1),
                Text = $"[color=#{color}]•[/color] [color=#{color}]{Loc.GetString(language)}[/color]",
            });
        }
    }

    /// <summary>
    /// Opens the dedicated species article on the Radiant Sector Fandom wiki.
    /// </summary>
    private void AddWikiLink(ProtoId<SpeciesPrototype> speciesId)
    {
        var page = speciesId.Id switch
        {
            "Human" => "Люди",
            "Reptilian" => "Унатхи",
            "SlimePerson" => "Слаймолюды",
            "Dwarf" => "Дворфы",
            "Diona" => "Дионы",
            "Vox" => "Воксы",
            "Moth" => "Нианы",
            "Arachnid" => "Арахниды",
            "Vulpkanin" => "Вульпканины",
            "Tajaran" => "Таяраны",
            "Oni" => "Они",
            "Felinid" => "Фелиниды",
            "Harpy" => "Гарпии",
            "Resomi" => "Резоми",
            "Goblin" => "Гоблины",
            "Sheleg" => "Шелеги",
            "Feroxi" => "Ферокси",
            "Shadowkin" => "Шадовкины",
            "DemonSpecies" => "Арканы",
            _ => null,
        };

        if (page == null)
            return;

        var wikiButton = new Button
        {
            Text = Loc.GetString("species-selection-wiki-link"),
            HorizontalExpand = true,
            Margin = new Thickness(2, 10, 2, 2),
        };
        var uri = $"https://radiantsector.fandom.com/ru/wiki/{Uri.EscapeDataString(page)}";
        wikiButton.OnPressed += _ => IoCManager.Resolve<IUriOpener>().OpenUri(uri);
        Details.AddChild(wikiButton);
    }

    private void UpdatePreview(ProtoId<SpeciesPrototype> species)
    {
        if (_previewEntity is { } oldPreview && _entities.EntityExists(oldPreview))
            _entities.DeleteEntity(oldPreview);

        _previewEntity = _lobby.LoadProfileEntity(_profile.WithSpecies(species), null, false);
        Preview.SetEntity(_previewEntity.Value);
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing && _previewEntity is { } preview && _entities.EntityExists(preview))
            _entities.DeleteEntity(preview);

        base.Dispose(disposing);
    }

    private sealed class SpeciesEntryButton(ProtoId<SpeciesPrototype> species) : Button
    {
        public ProtoId<SpeciesPrototype> Species { get; } = species;
    }
}
