using Content.Client.Humanoid;
using Content.Client.UserInterface.Controls;
using Content.Shared.Atmos;
using Content.Shared.Damage;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.IdentityManagement;
using Content.Shared.Mobs;
using Content.Shared.Mobs.Components;
using Content.Shared._Starlight.Medical.Surgery;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Map;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Starlight.Medical.Surgery.BodyScanner;

// Radiant sector start - large visual surgical report with a clothing-free patient preview.
[GenerateTypedNameReferences]
public sealed partial class BodyScannerWindow : FancyWindow
{
    private readonly IEntityManager _entities;
    private readonly IPrototypeManager _prototypes;
    private readonly HumanoidAppearanceSystem _appearance;
    private EntityUid? _previewDummy;
    private Direction _previewDirection = Direction.South;

    public BodyScannerWindow()
    {
        RobustXamlLoader.Load(this);
        _entities = IoCManager.Resolve<IEntityManager>();
        _prototypes = IoCManager.Resolve<IPrototypeManager>();
        _appearance = _entities.System<HumanoidAppearanceSystem>();
        RotatePatientLeftButton.OnPressed += _ => RotatePatient(-1);
        RotatePatientRightButton.OnPressed += _ => RotatePatient(1);
        ApplyPatientDirection();
        ShowNoPatient();
    }

    public void Populate(BodyScannerBoundUserInterfaceState state)
    {
        var target = _entities.GetEntity(state.Target);
        if (target is not { } patient
            || _entities.Deleted(patient)
            || !_entities.TryGetComponent<DamageableComponent>(patient, out var damageable))
        {
            ShowNoPatient();
            return;
        }

        PatientSprite.Visible = true;
        NoPatientTexture.Visible = false;
        PatientRotationControls.Visible = true;
        ConnectionState.Text = Loc.GetString("body-scanner-connected");
        ConnectionState.FontColorOverride = Color.LimeGreen;

        PatientName.Text = Identity.Name(patient, _entities);

        PatientSpecies.Text = _entities.TryGetComponent<HumanoidAppearanceComponent>(patient, out var humanoid)
            ? Loc.GetString(_prototypes.Index<SpeciesPrototype>(humanoid.Species).Name)
            : Loc.GetString("health-analyzer-window-entity-unknown-species-text");

        StatusLabel.Text = _entities.TryGetComponent<MobStateComponent>(patient, out var mob)
            ? GetStatus(mob.CurrentState)
            : Loc.GetString("health-analyzer-window-entity-unknown-text");
        TemperatureLabel.Text = !float.IsNaN(state.Temperature)
            ? $"{state.Temperature - Atmospherics.T0C:F1} °C ({state.Temperature:F1} K)"
            : Loc.GetString("health-analyzer-window-entity-unknown-value-text");
        BloodLabel.Text = !float.IsNaN(state.BloodLevel)
            ? $"{state.BloodLevel * 100:F1} %"
            : Loc.GetString("health-analyzer-window-entity-unknown-value-text");
        DamageLabel.Text = damageable.TotalDamage.ToString();
        BleedingAlert.Visible = state.Bleeding;

        SetPatientSprite(patient);
        DrawSurgicalDiagnostics(state.Diagnostics);
    }

    private void ShowNoPatient()
    {
        PatientSprite.Visible = false;
        NoPatientTexture.Visible = true;
        PatientRotationControls.Visible = false;
        PatientName.Text = Loc.GetString("body-scanner-no-patient");
        PatientSpecies.Text = string.Empty;
        ConnectionState.Text = Loc.GetString("body-scanner-disconnected");
        ConnectionState.FontColorOverride = Color.OrangeRed;
        StatusLabel.Text = "—";
        TemperatureLabel.Text = "—";
        BloodLabel.Text = "—";
        DamageLabel.Text = "—";
        BleedingAlert.Visible = false;
        SurgicalDiagnostics.RemoveAllChildren();
        AddDiagnostic(Loc.GetString("body-scanner-awaiting-patient"), Color.Gray);
    }

    private void DrawSurgicalDiagnostics(List<BodyScannerDiagnosticEntry> diagnostics)
    {
        SurgicalDiagnostics.RemoveAllChildren();

        if (diagnostics.Count == 0)
        {
            AddDiagnostic(Loc.GetString("health-analyzer-no-surgical-findings"), Color.LightGray);
            return;
        }

        foreach (var entry in diagnostics)
            AddDiagnostic(entry.Text, GetDiagnosticColor(entry.Severity));
    }

    private void AddDiagnostic(string text, Color color)
    {
        var message = new FormattedMessage();
        message.PushColor(color);
        message.AddText($"• {text}");
        var label = new RichTextLabel
        {
            SetWidth = 370,
        };
        label.SetMessage(message);
        SurgicalDiagnostics.AddChild(label);
    }

    private static Color GetDiagnosticColor(BodyScannerDiagnosticSeverity severity) => severity switch
    {
        BodyScannerDiagnosticSeverity.Critical => Color.Red,
        BodyScannerDiagnosticSeverity.Warning => Color.OrangeRed,
        BodyScannerDiagnosticSeverity.Cybernetic => Color.Cyan,
        BodyScannerDiagnosticSeverity.Implant => Color.LightBlue,
        BodyScannerDiagnosticSeverity.Anatomy => Color.LightPink,
        _ => Color.LightGray,
    };

    private void SetPatientSprite(EntityUid patient)
    {
        if (!_entities.TryGetComponent<HumanoidAppearanceComponent>(patient, out var source)
            || !_prototypes.TryIndex<SpeciesPrototype>(source.Species, out var species))
        {
            ClearPreviewDummy();
            PatientSprite.SetEntity(patient);
            return;
        }

        if (_previewDummy is not { } dummy
            || _entities.Deleted(dummy)
            || !_entities.TryGetComponent<HumanoidAppearanceComponent>(dummy, out var dummyAppearance)
            || dummyAppearance.Species != source.Species)
        {
            ClearPreviewDummy();
            dummy = _entities.SpawnEntity(species.DollPrototype, MapCoordinates.Nullspace);
            _previewDummy = dummy;
        }

        _appearance.CloneAppearance(patient, dummy, source);
        if (_entities.TryGetComponent<HumanoidAppearanceComponent>(dummy, out var preview))
        {
            preview.Height = source.Height;
            preview.Width = source.Width;
            preview.PermanentlyHidden = new(source.PermanentlyHidden);
        }

        _appearance.RefreshAppearance(dummy);
        PatientSprite.SetEntity(dummy);
        ApplyPatientDirection();
    }

    private void RotatePatient(int offset)
    {
        // Radiant sector: rotate only the scanner preview, never the real patient.
        var index = GetDirectionIndex(_previewDirection);
        index = (index + offset + 4) % 4;
        _previewDirection = GetDirection(index);
        ApplyPatientDirection();
    }

    private void ApplyPatientDirection()
    {
        PatientSprite.OverrideDirection = _previewDirection;
    }

    private static int GetDirectionIndex(Direction direction) => direction switch
    {
        Direction.South => 0,
        Direction.West => 1,
        Direction.North => 2,
        Direction.East => 3,
        _ => 0,
    };

    private static Direction GetDirection(int index) => index switch
    {
        1 => Direction.West,
        2 => Direction.North,
        3 => Direction.East,
        _ => Direction.South,
    };

    private void ClearPreviewDummy()
    {
        if (_previewDummy is { } dummy && !_entities.Deleted(dummy))
            _entities.DeleteEntity(dummy);
        _previewDummy = null;
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        if (disposing)
            ClearPreviewDummy();
    }

    private static string GetStatus(MobState state) => state switch
    {
        MobState.Alive => Loc.GetString("health-analyzer-window-entity-alive-text"),
        MobState.Critical => Loc.GetString("health-analyzer-window-entity-critical-text"),
        MobState.Dead => Loc.GetString("health-analyzer-window-entity-dead-text"),
        _ => Loc.GetString("health-analyzer-window-entity-unknown-text"),
    };

}
// Radiant sector end
