using Content.Client.Message;
using Content.Shared.Stacks;
using Content.Shared._radiant.Governor;
using Content.Shared._radiant.Governor.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._radiant.Governor.UI;

[GenerateTypedNameReferences]
public sealed partial class GovernorBountyEntry : BoxContainer
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    public Action? OnAcceptButtonPressed;
    public Action? OnSkipButtonPressed;

    public TimeSpan UntilNextSkip;

    public bool Accepted;

    public GovernorBountyEntry(GovernorBountyData bounty, TimeSpan untilNextSkip)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        UntilNextSkip = untilNextSkip;
        Accepted = bounty.Accepted;

        // Look up the bounty's prototype to fill in the labels.
        if (!_prototype.TryIndex<GovernorBountyPrototype>(bounty.Bounty, out var bountyPrototype))
            return;

        var items = new List<string>();
        foreach (var entry in bountyPrototype.Entries)
        {
            // Liquids show units ("150u"), items show count ("3x").
            items.Add(entry.Reagent != string.Empty
                ? Loc.GetString("governor-bounty-console-manifest-entry-liquid",
                    ("amount", entry.ReagentAmount),
                    ("item", Loc.GetString(entry.Name)))
                : Loc.GetString("governor-bounty-console-manifest-entry",
                    ("amount", entry.Amount),
                    ("item", Loc.GetString(entry.Name))));
        }
        ManifestLabel.SetMarkup(Loc.GetString("governor-bounty-console-manifest-label", ("item", string.Join(", ", items))));

        // Reward: credits + the name of the token stack (taken from the stack's own localization).
        var rewardText = Loc.GetString("governor-bounty-console-reward-label", ("reward", bountyPrototype.Reward));
        if (_prototype.TryIndex<StackPrototype>(bountyPrototype.TokenReward, out var tokenProto))
            rewardText += " " + Loc.GetString("governor-bounty-console-reward-token-suffix",
                ("count", bountyPrototype.TokenRewardCount),
                ("token", Loc.GetString(tokenProto.Name)));

        RewardLabel.SetMarkup(rewardText);
        DescriptionLabel.SetMarkup(Loc.GetString("governor-bounty-console-description-label", ("description", Loc.GetString(bountyPrototype.Description))));
        IdLabel.SetMarkup(Loc.GetString("governor-bounty-console-id-label", ("id", bounty.Id)));

        AcceptButton.OnPressed += _ => OnAcceptButtonPressed?.Invoke();
        SkipButton.OnPressed += _ => OnSkipButtonPressed?.Invoke();
    }

    private void UpdateAcceptButton()
    {
        AcceptButton.Disabled = Accepted;
        if (Accepted)
            AcceptButton.Label.Text = Loc.GetString("governor-bounty-console-accept-button-accepted");
        else
            AcceptButton.Label.Text = Loc.GetString("governor-bounty-console-accept-button-text");
    }

    private void UpdateSkipButton(float deltaSeconds)
    {
        UntilNextSkip -= TimeSpan.FromSeconds(deltaSeconds);
        if (UntilNextSkip > TimeSpan.Zero)
        {
            SkipButton.Label.Text = UntilNextSkip.ToString("mm\\:ss");
            SkipButton.Disabled = true;
            return;
        }

        SkipButton.Disabled = false;
        SkipButton.Label.Text = Loc.GetString("governor-bounty-console-skip-button-text");
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateSkipButton(args.DeltaSeconds);
        UpdateAcceptButton();
    }
}
