using Content.Client.UserInterface.Controls;
using Content.Shared._radiant.Governor;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._radiant.Governor.UI;

[GenerateTypedNameReferences]
public sealed partial class GovernorBountyMenu : FancyWindow
{
    public Action<string>? OnAcceptButtonPressed;
    public Action<string>? OnSkipButtonPressed;
    public Action? OnRedeemButtonPressed;

    public GovernorBountyMenu()
    {
        RobustXamlLoader.Load(this);
        RedeemButton.OnPressed += _ => OnRedeemButtonPressed?.Invoke();
    }

    public void UpdateEntries(List<GovernorBountyData> bounties, TimeSpan untilNextSkip)
    {
        GovernorBountyEntriesContainer.Children.Clear();
        foreach (var b in bounties)
        {
            var entry = new GovernorBountyEntry(b, untilNextSkip);
            entry.OnAcceptButtonPressed += () => OnAcceptButtonPressed?.Invoke(b.Id);
            entry.OnSkipButtonPressed += () => OnSkipButtonPressed?.Invoke(b.Id);

            GovernorBountyEntriesContainer.AddChild(entry);
        }
        GovernorBountyEntriesContainer.AddChild(new Control
        {
            MinHeight = 10
        });
    }
}
