- type: job
  id: Sheriff
  name: job-name-sheriff
  description: job-description-sheriff
  playTimeTracker: JobHeadOfSecurity
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 72000 # 20 hours Radiant_Sector
    - !type:DepartmentTimeRequirement
      department: Security
      time: 36000 # 10 hours Radiant_Sector
    - !type:RoleTimeRequirement
      role: JobWarden
      time: 21600 # 6 hours Radiant_Sector
    - !type:RoleTimeRequirement
      role: JobSeniorOfficer
      time: 21600 # 6 hours Radiant_Sector
  alternateRequirementSets:
    longerPlaytimeLessSec:
    - !type:OverallPlaytimeRequirement
      time: 360000 # 100 hours Radiant_Sector
    - !type:DepartmentTimeRequirement
      department: Security
      time: 72000 # 20 hours Radiant_Sector
  whitelisted: true
  startingGear: SheriffGear
  alwaysUseSpawner: true
  icon: JobIconSheriff
  requireAdminNotify: true
  supervisors: job-supervisors-centcom
  weight: 180
  displayWeight: 70
  canBeAntag: false
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      - type: PreventShipyardTitleOverwrite
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: SheriffGear
  equipment:
    pocket1: NFWeaponPistolUniversalNfsdLessLethal
    pocket2: NFWeaponEnergyPistolLaserX01Multiphase
  storage:
    back:
    - NfsdTechFabFlatpack
    - Multitool
    - HoloprojectorNfsd
    - DoorRemoteNfsd
    - BaseSecurityUplinkRadioSheriff
    - RubberStampSheriff

- type: chameleonOutfit
  id: SheriffChameleonOutfit
  job: Sheriff
  hasMindShield: true
  equipment:
    head: ClothingHeadHatNfsdCampaignFilled
    mask: ClothingMaskGasSheriff
    eyes: ClothingEyesGlassesNfsd
    outerClothing: ClothingOuterCoatNfsdFormalSheriff
    neck: ClothingNeckNfsdBadgeSheriff
    belt: ClothingBeltNfsdFilled
    gloves: ClothingHandsGlovesCombatNfsdCream
    shoes: ClothingShoesBootsNfsdBrown
