- type: job
  id: NavyBrigmedic
  name: job-name-navy-brigmedic
  description: job-description-navy-brigmedic
  playTimeTracker: JobBrigmedic
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 14400 # 4 hours Radiant_Sector
    - !type:DepartmentTimeRequirement
      department: Security
      time: 3600 # 1 hours Radiant_Sector
  startingGear: NavyBrigmedicGear
  icon: "JobIconNavyBrigmedic"
  supervisors: job-supervisors-bailiff
  weight: 125
  displayWeight: 35
  canBeAntag: false
  access:
  - Brigmedic
  accessGroups:
  - NavyOfficerAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplantNavy ]
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: NavyBrigmedicGear
  equipment:
    pocket1: WeaponPistolMk58 #WeaponPistolMk58Nonlethal
  storage:
    back:
    - EncryptionKeyMedical
    - Flash
    - MagazinePistol
    - MagazinePistolRubber
    - FrontierUplinkCoin10
    - NavyToken1
    - NFPouchNavy
