using System;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.DetailExaminable;
using Content.Shared.Humanoid;
using Content.Shared.IdentityManagement;
using Content.Shared._radiant;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.DetailExaminable;

[GenerateTypedNameReferences]
public sealed partial class DetailExaminableWindow : FancyWindow
{
    public DetailExaminableWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(DetailExaminableComponent detail, EntityUid target, IEntityManager entManager)
    {
        PreviewTabs.SetTabTitle(0, Loc.GetString("flavor-tab-flavor"));
        PreviewTabs.SetTabTitle(1, Loc.GetString("flavor-tab-character"));
        PreviewTabs.SetTabTitle(2, Loc.GetString("flavor-tab-gyr"));
        PreviewTabs.SetTabTitle(3, Loc.GetString("flavor-tab-nsfw"));

        if (entManager.TryGetComponent<HumanoidAppearanceComponent>(target, out var humanoid))
        {
            var species = Loc.GetString($"species-name-{humanoid.Species.ToString().ToLowerInvariant()}");
            var sex = Loc.GetString($"humanoid-profile-editor-sex-{humanoid.Sex.ToString().ToLowerInvariant()}-text");
            var gender = Loc.GetString($"humanoid-profile-editor-pronouns-{humanoid.Gender.ToString().ToLowerInvariant()}-text");
            PreviewGenderText.Text = $"{species}|{sex}|{gender}";
        }
        else
        {
            PreviewGenderText.Text = string.Empty;
        }

        PreviewNameText.Text = Identity.Name(target, entManager);
        PreviewERPStatusText.Text = GetStatusText(detail.ERPStatus);
        PreviewERPStatusText.FontColorOverride = GetStatusColor(detail.ERPStatus);
        TargetPreview.SetEntity(target);

        PreviewAppearanceText.SetMessage(FormattedMessage.FromMarkupPermissive(detail.Content));
        PreviewTraitsText.SetMessage(FormattedMessage.FromMarkupPermissive(detail.CharacterFlavorText));
        PreviewOOCText.SetMessage(FormattedMessage.FromMarkupPermissive(detail.OOCFlavorText));
        PreviewNSFWText.SetMessage(FormattedMessage.FromMarkupPermissive(detail.NSFWFlavorText));

        PreviewGYRContainer.RemoveAllChildren();
        CreateGYRBigTextLabel(Loc.GetString("humanoid-profile-editor-gyr-green"), Color.Green);
        CreateGYRTextLabel(detail.GreenFlavorText);
        CreateGYRBigTextLabel(Loc.GetString("humanoid-profile-editor-gyr-yellow"), Color.Yellow);
        CreateGYRTextLabel(detail.YellowFlavorText);
        CreateGYRBigTextLabel(Loc.GetString("humanoid-profile-editor-gyr-red"), Color.Red);
        CreateGYRTextLabel(detail.RedFlavorText);

        PreviewTagsText.Text = detail.TagsFlavorText;
        ProcessLinks(detail.LinksFlavorText);
    }

    private static string GetStatusText(EnumERPStatus status)
    {
        return status switch
        {
            EnumERPStatus.FULL => Loc.GetString("humanoid-erp-status-full"),
            EnumERPStatus.HALF => Loc.GetString("humanoid-erp-status-half"),
            _ => Loc.GetString("humanoid-erp-status-no")
        };
    }

    private static Color GetStatusColor(EnumERPStatus status)
    {
        return status switch
        {
            EnumERPStatus.FULL => Color.Green,
            EnumERPStatus.HALF => Color.Yellow,
            _ => Color.Red
        };
    }

    private void CreateGYRBigTextLabel(string text, Color color)
    {
        var label = new Label
        {
            Text = text,
            VerticalExpand = true,
            StyleClasses = { "LabelHeading" },
            FontColorOverride = color
        };

        PreviewGYRContainer.AddChild(label);
    }

    private void CreateGYRTextLabel(string text)
    {
        var label = new RichTextLabel
        {
            Text = text + "\n",
            VerticalExpand = true
        };

        PreviewGYRContainer.AddChild(label);
    }

    private void ProcessLinks(string linksText)
    {
        PreviewLinksContainer.RemoveAllChildren();
        if (string.IsNullOrWhiteSpace(linksText))
            return;

        var links = linksText.Split(new[] { ',', ' ', '\n', '\r', '\t' }, StringSplitOptions.RemoveEmptyEntries);
        foreach (var link in links)
        {
            if (IsValidUrl(link))
                CreateLinkButton(link);
            else
                CreateLinkTextLabel(link);
        }
    }

    private static bool IsValidUrl(string url)
    {
        return url.StartsWith("http://", StringComparison.OrdinalIgnoreCase) ||
               url.StartsWith("https://", StringComparison.OrdinalIgnoreCase) ||
               url.StartsWith("www.", StringComparison.OrdinalIgnoreCase);
    }

    private void CreateLinkButton(string url)
    {
        var button = new Button
        {
            Text = GetLinkDisplayText(url),
            ToolTip = Loc.GetString("humanoid-profile-editor-link-tooltip", ("url", url)),
            HorizontalExpand = true,
            HorizontalAlignment = HAlignment.Center,
            StyleClasses = { "ButtonOpenBoth" }
        };

        button.OnPressed += _ => OpenLink(url);
        PreviewLinksContainer.AddChild(button);
    }

    private void CreateLinkTextLabel(string text)
    {
        var label = new Label
        {
            Text = text,
            HorizontalExpand = true,
            HorizontalAlignment = HAlignment.Center,
            FontColorOverride = Color.Gray
        };

        PreviewLinksContainer.AddChild(label);
    }

    private static string GetLinkDisplayText(string url)
    {
        return url.Length > 40 ? url[..37] + "..." : url;
    }

    private static void OpenLink(string url)
    {
        if (url.StartsWith("www.", StringComparison.OrdinalIgnoreCase))
            url = "https://" + url;

        var uriOpener = IoCManager.Resolve<IUriOpener>();
        uriOpener.OpenUri(url);
    }
}
